/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorVO,
  GetAllPromotionsParams,
  PageVO,
  PromotionRequestDTO,
  PromotionResponseDTO
} from '../../types';





/**
 * Retrieve a promotion by its ID
 * @summary Get promotion by ID
 */
export const getPromotionById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PromotionResponseDTO>> => {
    
    
    return axios.default.get(
      `/api/v1/promotions/${id}`,options
    );
  }




export const getGetPromotionByIdQueryKey = (id?: number,) => {
    return [
    `/api/v1/promotions/${id}`
    ] as const;
    }

    
export const getGetPromotionByIdQueryOptions = <TData = Awaited<ReturnType<typeof getPromotionById>>, TError = AxiosError<ErrorVO | void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPromotionById>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPromotionByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPromotionById>>> = ({ signal }) => getPromotionById(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPromotionById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPromotionByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPromotionById>>>
export type GetPromotionByIdQueryError = AxiosError<ErrorVO | void>


/**
 * @summary Get promotion by ID
 */

export function useGetPromotionById<TData = Awaited<ReturnType<typeof getPromotionById>>, TError = AxiosError<ErrorVO | void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPromotionById>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPromotionByIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Only accessible by admin
 * @summary Update a promotion
 */
export const updatePromotion = (
    id: number,
    promotionRequestDTO: PromotionRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PromotionResponseDTO>> => {
    
    
    return axios.default.put(
      `/api/v1/promotions/${id}`,
      promotionRequestDTO,options
    );
  }



export const getUpdatePromotionMutationOptions = <TError = AxiosError<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePromotion>>, TError,{id: number;data: PromotionRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updatePromotion>>, TError,{id: number;data: PromotionRequestDTO}, TContext> => {

const mutationKey = ['updatePromotion'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePromotion>>, {id: number;data: PromotionRequestDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePromotion(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePromotionMutationResult = NonNullable<Awaited<ReturnType<typeof updatePromotion>>>
    export type UpdatePromotionMutationBody = PromotionRequestDTO
    export type UpdatePromotionMutationError = AxiosError<ErrorVO | void>

    /**
 * @summary Update a promotion
 */
export const useUpdatePromotion = <TError = AxiosError<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePromotion>>, TError,{id: number;data: PromotionRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updatePromotion>>,
        TError,
        {id: number;data: PromotionRequestDTO},
        TContext
      > => {

      const mutationOptions = getUpdatePromotionMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Only accessible by admin
 * @summary Delete a promotion
 */
export const deletePromotion = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/v1/promotions/${id}`,options
    );
  }



export const getDeletePromotionMutationOptions = <TError = AxiosError<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePromotion>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deletePromotion>>, TError,{id: number}, TContext> => {

const mutationKey = ['deletePromotion'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePromotion>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deletePromotion(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePromotionMutationResult = NonNullable<Awaited<ReturnType<typeof deletePromotion>>>
    
    export type DeletePromotionMutationError = AxiosError<ErrorVO | void>

    /**
 * @summary Delete a promotion
 */
export const useDeletePromotion = <TError = AxiosError<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePromotion>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deletePromotion>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeletePromotionMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Retrieve a paginated list of promotions with optional filtering
 * @summary Get all promotions
 */
export const getAllPromotions = (
    params: GetAllPromotionsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PageVO>> => {
    
    
    return axios.default.get(
      `/api/v1/promotions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAllPromotionsQueryKey = (params?: GetAllPromotionsParams,) => {
    return [
    `/api/v1/promotions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllPromotionsQueryOptions = <TData = Awaited<ReturnType<typeof getAllPromotions>>, TError = AxiosError<ErrorVO>>(params: GetAllPromotionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllPromotions>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllPromotionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllPromotions>>> = ({ signal }) => getAllPromotions(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllPromotions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllPromotionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllPromotions>>>
export type GetAllPromotionsQueryError = AxiosError<ErrorVO>


/**
 * @summary Get all promotions
 */

export function useGetAllPromotions<TData = Awaited<ReturnType<typeof getAllPromotions>>, TError = AxiosError<ErrorVO>>(
 params: GetAllPromotionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllPromotions>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllPromotionsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Only accessible by admin
 * @summary Create a new promotion
 */
export const createPromotion = (
    promotionRequestDTO: PromotionRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PromotionResponseDTO>> => {
    
    
    return axios.default.post(
      `/api/v1/promotions`,
      promotionRequestDTO,options
    );
  }



export const getCreatePromotionMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPromotion>>, TError,{data: PromotionRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createPromotion>>, TError,{data: PromotionRequestDTO}, TContext> => {

const mutationKey = ['createPromotion'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPromotion>>, {data: PromotionRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  createPromotion(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePromotionMutationResult = NonNullable<Awaited<ReturnType<typeof createPromotion>>>
    export type CreatePromotionMutationBody = PromotionRequestDTO
    export type CreatePromotionMutationError = AxiosError<ErrorVO>

    /**
 * @summary Create a new promotion
 */
export const useCreatePromotion = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPromotion>>, TError,{data: PromotionRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createPromotion>>,
        TError,
        {data: PromotionRequestDTO},
        TContext
      > => {

      const mutationOptions = getCreatePromotionMutationOptions(options);

      return useMutation(mutationOptions);
    }
    