/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Retrieve a promotion by its ID
 * @summary Get promotion by ID
 */
export const getPromotionByIdParams = zod.object({
  "id": zod.number()
})

/**
 * Only accessible by admin
 * @summary Update a promotion
 */
export const updatePromotionParams = zod.object({
  "id": zod.number()
})

export const updatePromotionBody = zod.object({
  "description": zod.string().optional(),
  "discountValue": zod.number(),
  "minValue": zod.number(),
  "startDate": zod.iso.datetime({}),
  "endDate": zod.iso.datetime({}),
  "code": zod.string().optional(),
  "isPublic": zod.boolean().optional(),
  "userIds": zod.array(zod.number()).optional()
})

/**
 * Only accessible by admin
 * @summary Delete a promotion
 */
export const deletePromotionParams = zod.object({
  "id": zod.number()
})

/**
 * Retrieve a paginated list of promotions with optional filtering
 * @summary Get all promotions
 */
export const getAllPromotionsQueryPageDefault = 0;
export const getAllPromotionsQueryPageMin = 0;

export const getAllPromotionsQuerySizeDefault = 20;



export const getAllPromotionsQueryParams = zod.object({
  "page": zod.number().min(getAllPromotionsQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getAllPromotionsQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.object({

})
})

/**
 * Only accessible by admin
 * @summary Create a new promotion
 */
export const createPromotionBody = zod.object({
  "description": zod.string().optional(),
  "discountValue": zod.number(),
  "minValue": zod.number(),
  "startDate": zod.iso.datetime({}),
  "endDate": zod.iso.datetime({}),
  "code": zod.string().optional(),
  "isPublic": zod.boolean().optional(),
  "userIds": zod.array(zod.number()).optional()
})

