/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetEnums200,
  GetEnumsParams
} from '../../types';





/**
 * Retrieve all enums available in the application. Optionally filter by types. 
Available types: OTP_ACTION, ROLE_NAME, USER_STATUS, ORDER_STATUS, PAYMENT_METHOD
 * @summary Get all enums
 */
export const getEnums = (
    params?: GetEnumsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetEnums200>> => {
    
    
    return axios.default.get(
      `/api/v1/metadata`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetEnumsQueryKey = (params?: GetEnumsParams,) => {
    return [
    `/api/v1/metadata`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetEnumsQueryOptions = <TData = Awaited<ReturnType<typeof getEnums>>, TError = AxiosError<unknown>>(params?: GetEnumsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnums>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEnumsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnums>>> = ({ signal }) => getEnums(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEnums>>, TError, TData> & { queryKey: QueryKey }
}

export type GetEnumsQueryResult = NonNullable<Awaited<ReturnType<typeof getEnums>>>
export type GetEnumsQueryError = AxiosError<unknown>


/**
 * @summary Get all enums
 */

export function useGetEnums<TData = Awaited<ReturnType<typeof getEnums>>, TError = AxiosError<unknown>>(
 params?: GetEnumsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnums>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetEnumsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




