/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Retrieve all enums available in the application. Optionally filter by types. 
Available types: OTP_ACTION, ROLE_NAME, USER_STATUS, ORDER_STATUS, PAYMENT_METHOD
 * @summary Get all enums
 */
export const getEnumsQueryParams = zod.object({
  "types": zod.array(zod.enum(['OTP_ACTION', 'ORDER_STATUS', 'PAYMENT_METHOD', 'USER_STATUS', 'ROLE_NAME'])).optional()
})

