/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DeliveryRequestDTO,
  DeliveryResponseDTO
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get delivery estimates based on the given origin and destination coordinates
 * @summary Get delivery estimates
 */
export const estimateTime = (
    deliveryRequestDTO: BodyType<DeliveryRequestDTO>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<DeliveryResponseDTO>(
      {url: `/api/v1/delivery/estimate-time`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deliveryRequestDTO, signal
    },
      options);
    }
  


export const getEstimateTimeMutationOptions = <TError = ErrorType<DeliveryResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof estimateTime>>, TError,{data: BodyType<DeliveryRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof estimateTime>>, TError,{data: BodyType<DeliveryRequestDTO>}, TContext> => {

const mutationKey = ['estimateTime'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof estimateTime>>, {data: BodyType<DeliveryRequestDTO>}> = (props) => {
          const {data} = props ?? {};

          return  estimateTime(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EstimateTimeMutationResult = NonNullable<Awaited<ReturnType<typeof estimateTime>>>
    export type EstimateTimeMutationBody = BodyType<DeliveryRequestDTO>
    export type EstimateTimeMutationError = ErrorType<DeliveryResponseDTO>

    /**
 * @summary Get delivery estimates
 */
export const useEstimateTime = <TError = ErrorType<DeliveryResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof estimateTime>>, TError,{data: BodyType<DeliveryRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof estimateTime>>,
        TError,
        {data: BodyType<DeliveryRequestDTO>},
        TContext
      > => {

      const mutationOptions = getEstimateTimeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    