/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Get delivery estimates based on the given origin and destination coordinates
 * @summary Get delivery estimates
 */
export const estimateTimeBody = zod.object({
  "destinationLat": zod.number().optional(),
  "destinationLng": zod.number().optional()
})

