/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorVO,
  GetAllOrdersParams,
  GetMyOrdersParams,
  OrderRequestDTO,
  OrderResponseDTO,
  PageVO,
  PageVOOrderResponseDTO,
  UpdateStatus1Params
} from '../../types';





/**
 * Mark a specific order as delivered
 * @summary Mark an order as delivered
 */
export const markOrderAsDelivered = (
    orderId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.put(
      `/api/v1/orders/${orderId}/delivered`,undefined,{
    ...options,}
    );
  }



export const getMarkOrderAsDeliveredMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markOrderAsDelivered>>, TError,{orderId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof markOrderAsDelivered>>, TError,{orderId: number}, TContext> => {

const mutationKey = ['markOrderAsDelivered'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markOrderAsDelivered>>, {orderId: number}> = (props) => {
          const {orderId} = props ?? {};

          return  markOrderAsDelivered(orderId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarkOrderAsDeliveredMutationResult = NonNullable<Awaited<ReturnType<typeof markOrderAsDelivered>>>
    
    export type MarkOrderAsDeliveredMutationError = AxiosError<ErrorVO>

    /**
 * @summary Mark an order as delivered
 */
export const useMarkOrderAsDelivered = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markOrderAsDelivered>>, TError,{orderId: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof markOrderAsDelivered>>,
        TError,
        {orderId: number},
        TContext
      > => {

      const mutationOptions = getMarkOrderAsDeliveredMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Update the order data by its ID
 * @summary Update an order
 */
export const updateOrder = (
    id: number,
    orderRequestDTO: OrderRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrderResponseDTO>> => {
    
    
    return axios.default.put(
      `/api/v1/orders/update/${id}`,
      orderRequestDTO,options
    );
  }



export const getUpdateOrderMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrder>>, TError,{id: number;data: OrderRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateOrder>>, TError,{id: number;data: OrderRequestDTO}, TContext> => {

const mutationKey = ['updateOrder'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrder>>, {id: number;data: OrderRequestDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOrder(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrderMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrder>>>
    export type UpdateOrderMutationBody = OrderRequestDTO
    export type UpdateOrderMutationError = AxiosError<ErrorVO>

    /**
 * @summary Update an order
 */
export const useUpdateOrder = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrder>>, TError,{id: number;data: OrderRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateOrder>>,
        TError,
        {id: number;data: OrderRequestDTO},
        TContext
      > => {

      const mutationOptions = getUpdateOrderMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Create a new order from cart or manual input
 * @summary Create a new order
 */
export const createOrder = (
    orderRequestDTO: OrderRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrderResponseDTO>> => {
    
    
    return axios.default.post(
      `/api/v1/orders/create`,
      orderRequestDTO,options
    );
  }



export const getCreateOrderMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: OrderRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: OrderRequestDTO}, TContext> => {

const mutationKey = ['createOrder'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrder>>, {data: OrderRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  createOrder(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOrderMutationResult = NonNullable<Awaited<ReturnType<typeof createOrder>>>
    export type CreateOrderMutationBody = OrderRequestDTO
    export type CreateOrderMutationError = AxiosError<ErrorVO>

    /**
 * @summary Create a new order
 */
export const useCreateOrder = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: OrderRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createOrder>>,
        TError,
        {data: OrderRequestDTO},
        TContext
      > => {

      const mutationOptions = getCreateOrderMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Cancel an order by its ID
 * @summary Cancel an order
 */
export const cancelOrder = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/v1/orders/cancel/${id}`,undefined,options
    );
  }



export const getCancelOrderMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelOrder>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof cancelOrder>>, TError,{id: number}, TContext> => {

const mutationKey = ['cancelOrder'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelOrder>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  cancelOrder(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CancelOrderMutationResult = NonNullable<Awaited<ReturnType<typeof cancelOrder>>>
    
    export type CancelOrderMutationError = AxiosError<ErrorVO>

    /**
 * @summary Cancel an order
 */
export const useCancelOrder = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelOrder>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof cancelOrder>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getCancelOrderMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Retrieve a paginated list of orders with optional filters
 * @summary Get all orders with filtering and pagination
 */
export const getAllOrders = (
    params: GetAllOrdersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PageVOOrderResponseDTO>> => {
    
    
    return axios.default.get(
      `/api/v1/orders`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAllOrdersQueryKey = (params?: GetAllOrdersParams,) => {
    return [
    `/api/v1/orders`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getAllOrders>>, TError = AxiosError<ErrorVO>>(params: GetAllOrdersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllOrders>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllOrdersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllOrders>>> = ({ signal }) => getAllOrders(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllOrders>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllOrders>>>
export type GetAllOrdersQueryError = AxiosError<ErrorVO>


/**
 * @summary Get all orders with filtering and pagination
 */

export function useGetAllOrders<TData = Awaited<ReturnType<typeof getAllOrders>>, TError = AxiosError<ErrorVO>>(
 params: GetAllOrdersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllOrders>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update the status of an order by its ID
 * @summary Update order status
 */
export const updateStatus1 = (
    orderId: number,
    params: UpdateStatus1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/api/v1/orders/${orderId}/status`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getUpdateStatus1QueryKey = (orderId?: number,
    params?: UpdateStatus1Params,) => {
    return [
    `/api/v1/orders/${orderId}/status`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getUpdateStatus1QueryOptions = <TData = Awaited<ReturnType<typeof updateStatus1>>, TError = AxiosError<ErrorVO>>(orderId: number,
    params: UpdateStatus1Params, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof updateStatus1>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateStatus1QueryKey(orderId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateStatus1>>> = ({ signal }) => updateStatus1(orderId,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(orderId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateStatus1>>, TError, TData> & { queryKey: QueryKey }
}

export type UpdateStatus1QueryResult = NonNullable<Awaited<ReturnType<typeof updateStatus1>>>
export type UpdateStatus1QueryError = AxiosError<ErrorVO>


/**
 * @summary Update order status
 */

export function useUpdateStatus1<TData = Awaited<ReturnType<typeof updateStatus1>>, TError = AxiosError<ErrorVO>>(
 orderId: number,
    params: UpdateStatus1Params, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof updateStatus1>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUpdateStatus1QueryOptions(orderId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retrieve an order by its ID
 * @summary Get order by ID
 */
export const findById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrderResponseDTO>> => {
    
    
    return axios.default.get(
      `/api/v1/orders/${id}`,options
    );
  }




export const getFindByIdQueryKey = (id?: number,) => {
    return [
    `/api/v1/orders/${id}`
    ] as const;
    }

    
export const getFindByIdQueryOptions = <TData = Awaited<ReturnType<typeof findById>>, TError = AxiosError<ErrorVO>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof findById>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findById>>> = ({ signal }) => findById(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findById>>, TError, TData> & { queryKey: QueryKey }
}

export type FindByIdQueryResult = NonNullable<Awaited<ReturnType<typeof findById>>>
export type FindByIdQueryError = AxiosError<ErrorVO>


/**
 * @summary Get order by ID
 */

export function useFindById<TData = Awaited<ReturnType<typeof findById>>, TError = AxiosError<ErrorVO>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof findById>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFindByIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retrieve paginated and filtered orders for the current user.
 * @summary Get current user's orders
 */
export const getMyOrders = (
    params: GetMyOrdersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PageVO>> => {
    
    
    return axios.default.get(
      `/api/v1/orders/me`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetMyOrdersQueryKey = (params?: GetMyOrdersParams,) => {
    return [
    `/api/v1/orders/me`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetMyOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getMyOrders>>, TError = AxiosError<ErrorVO>>(params: GetMyOrdersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMyOrders>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyOrdersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyOrders>>> = ({ signal }) => getMyOrders(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyOrders>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMyOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getMyOrders>>>
export type GetMyOrdersQueryError = AxiosError<ErrorVO>


/**
 * @summary Get current user's orders
 */

export function useGetMyOrders<TData = Awaited<ReturnType<typeof getMyOrders>>, TError = AxiosError<ErrorVO>>(
 params: GetMyOrdersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMyOrders>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMyOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Delete an order by its ID
 * @summary Delete an order
 */
export const deleteOrder = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/v1/orders/delete/${id}`,options
    );
  }



export const getDeleteOrderMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrder>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteOrder>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteOrder'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOrder>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteOrder(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOrderMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOrder>>>
    
    export type DeleteOrderMutationError = AxiosError<ErrorVO>

    /**
 * @summary Delete an order
 */
export const useDeleteOrder = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrder>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteOrder>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteOrderMutationOptions(options);

      return useMutation(mutationOptions);
    }
    