/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Mark a specific order as delivered
 * @summary Mark an order as delivered
 */
export const markOrderAsDeliveredParams = zod.object({
  "orderId": zod.number()
})

/**
 * Update the order data by its ID
 * @summary Update an order
 */
export const updateOrderParams = zod.object({
  "id": zod.number()
})

export const updateOrderBody = zod.object({
  "destinationLatitude": zod.number(),
  "destinationLongitude": zod.number(),
  "shippingAddress": zod.string(),
  "note": zod.string().optional(),
  "paymentMethod": zod.enum(['CASH_ON_DELIVERY', 'VNPAY']),
  "promotionId": zod.number().optional()
})

/**
 * Create a new order from cart or manual input
 * @summary Create a new order
 */
export const createOrderBody = zod.object({
  "destinationLatitude": zod.number(),
  "destinationLongitude": zod.number(),
  "shippingAddress": zod.string(),
  "note": zod.string().optional(),
  "paymentMethod": zod.enum(['CASH_ON_DELIVERY', 'VNPAY']),
  "promotionId": zod.number().optional()
})

/**
 * Cancel an order by its ID
 * @summary Cancel an order
 */
export const cancelOrderParams = zod.object({
  "id": zod.number()
})

/**
 * Retrieve a paginated list of orders with optional filters
 * @summary Get all orders with filtering and pagination
 */
export const getAllOrdersQueryPageDefault = 0;
export const getAllOrdersQueryPageMin = 0;

export const getAllOrdersQuerySizeDefault = 20;



export const getAllOrdersQueryParams = zod.object({
  "page": zod.number().min(getAllOrdersQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getAllOrdersQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.object({

})
})

/**
 * Update the status of an order by its ID
 * @summary Update order status
 */
export const updateStatus1Params = zod.object({
  "orderId": zod.number()
})

export const updateStatus1QueryParams = zod.object({
  "status": zod.enum(['PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPING', 'COMPLETED', 'CANCELED'])
})

/**
 * Retrieve an order by its ID
 * @summary Get order by ID
 */
export const findByIdParams = zod.object({
  "id": zod.number()
})

/**
 * Retrieve paginated and filtered orders for the current user.
 * @summary Get current user's orders
 */
export const getMyOrdersQueryPageDefault = 0;
export const getMyOrdersQueryPageMin = 0;

export const getMyOrdersQuerySizeDefault = 20;



export const getMyOrdersQueryParams = zod.object({
  "page": zod.number().min(getMyOrdersQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getMyOrdersQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.object({

})
})

/**
 * Delete an order by its ID
 * @summary Delete an order
 */
export const deleteOrderParams = zod.object({
  "id": zod.number()
})

