/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Retrieve a role by its ID. Only accessible to users with the ADMIN role.
 * @summary Get role by ID
 */
export const getRoleByIdParams = zod.object({
  "id": zod.number()
})

/**
 * Update an existing role. Only accessible to users with the ADMIN role.
 * @summary Update a role
 */
export const updateRoleParams = zod.object({
  "id": zod.number()
})

export const updateRoleBody = zod.object({
  "name": zod.string(),
  "description": zod.string().optional(),
  "active": zod.boolean().optional()
})

/**
 * Delete a role by its ID. Only accessible to users with the ADMIN role.
 * @summary Delete a role
 */
export const deleteRoleParams = zod.object({
  "id": zod.number()
})

/**
 * Retrieve a paginated list of all roles. Only accessible to users with the ADMIN role.
 * @summary Get all roles
 */
export const getAllRolesQueryPageDefault = 0;
export const getAllRolesQueryPageMin = 0;

export const getAllRolesQuerySizeDefault = 20;



export const getAllRolesQueryParams = zod.object({
  "page": zod.number().min(getAllRolesQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getAllRolesQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.object({

})
})

/**
 * Create a new role. Only accessible to users with the ADMIN role.
 * @summary Create a new role
 */
export const createRoleBody = zod.object({
  "name": zod.string(),
  "description": zod.string().optional(),
  "active": zod.boolean().optional()
})

