/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Retrieve a product by its ID
 * @summary Get product by ID
 */
export const getProductByIdParams = zod.object({
  "id": zod.number()
})

/**
 * Update an existing product entry
 * @summary Update a product
 */
export const updateProductParams = zod.object({
  "id": zod.number()
})

export const updateProductBody = zod.object({
  "categoryId": zod.number().optional(),
  "name": zod.string().optional(),
  "shortDescription": zod.string().optional(),
  "detailDescription": zod.string().optional(),
  "originalPrice": zod.number().optional(),
  "image": zod.instanceof(File).optional()
})

/**
 * Delete a product by its ID
 * @summary Delete a product
 */
export const deleteProductParams = zod.object({
  "id": zod.number()
})

/**
 * Retrieve a list of all products with optional filtering
 * @summary Get all products
 */
export const getAllProductsQueryPageDefault = 0;
export const getAllProductsQueryPageMin = 0;

export const getAllProductsQuerySizeDefault = 20;



export const getAllProductsQueryParams = zod.object({
  "page": zod.number().min(getAllProductsQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getAllProductsQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.object({

})
})

/**
 * Create a new product entry
 * @summary Create a new product
 */
export const createProductBody = zod.object({
  "categoryId": zod.number().optional(),
  "name": zod.string().optional(),
  "shortDescription": zod.string().optional(),
  "detailDescription": zod.string().optional(),
  "originalPrice": zod.number().optional(),
  "image": zod.instanceof(File).optional()
})

/**
 * Retrieve a list of products by category ID
 * @summary Get products by category
 */
export const getProductsByCategoryParams = zod.object({
  "id": zod.number()
})

export const getProductsByCategoryQueryPageDefault = 0;
export const getProductsByCategoryQueryPageMin = 0;

export const getProductsByCategoryQuerySizeDefault = 20;



export const getProductsByCategoryQueryParams = zod.object({
  "page": zod.number().min(getProductsByCategoryQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getProductsByCategoryQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.')
})

