/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorVO,
  GetAllUsersParams,
  PageVO,
  UpdateStatusParams,
  UserRequestDTO,
  UserResponseDTO
} from '../../types';





/**
 * Retrieve a user by their ID
 * @summary Get user by ID
 */
export const getUserById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponseDTO>> => {
    
    
    return axios.default.get(
      `/api/v1/users/${id}`,options
    );
  }




export const getGetUserByIdQueryKey = (id?: number,) => {
    return [
    `/api/v1/users/${id}`
    ] as const;
    }

    
export const getGetUserByIdQueryOptions = <TData = Awaited<ReturnType<typeof getUserById>>, TError = AxiosError<ErrorVO>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserById>>> = ({ signal }) => getUserById(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUserById>>>
export type GetUserByIdQueryError = AxiosError<ErrorVO>


/**
 * @summary Get user by ID
 */

export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = AxiosError<ErrorVO>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserByIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing user by their ID
 * @summary Update user
 */
export const updateUser = (
    id: number,
    userRequestDTO: UserRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponseDTO>> => {
    
    const formData = new FormData();
formData.append(`fullname`, userRequestDTO.fullname)
formData.append(`username`, userRequestDTO.username)
formData.append(`email`, userRequestDTO.email)
if(userRequestDTO.phone !== undefined) {
 formData.append(`phone`, userRequestDTO.phone)
 }
if(userRequestDTO.avatar !== undefined) {
 formData.append(`avatar`, userRequestDTO.avatar)
 }
formData.append(`roleId`, userRequestDTO.roleId.toString())

    return axios.default.put(
      `/api/v1/users/${id}`,
      formData,options
    );
  }



export const getUpdateUserMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: UserRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: UserRequestDTO}, TContext> => {

const mutationKey = ['updateUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUser>>, {id: number;data: UserRequestDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  updateUser(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
    export type UpdateUserMutationBody = UserRequestDTO
    export type UpdateUserMutationError = AxiosError<ErrorVO>

    /**
 * @summary Update user
 */
export const useUpdateUser = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: UserRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {id: number;data: UserRequestDTO},
        TContext
      > => {

      const mutationOptions = getUpdateUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Delete a user by their ID
 * @summary Delete user
 */
export const deleteUser = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/v1/users/${id}`,options
    );
  }



export const getDeleteUserMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteUser(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    
    export type DeleteUserMutationError = AxiosError<ErrorVO>

    /**
 * @summary Delete user
 */
export const useDeleteUser = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Assign a role to a user by their ID
 * @summary Assign role to user
 */
export const assignRoleToUser = (
    id: number,
    roleId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/v1/users/${id}/assign-role/${roleId}`,undefined,options
    );
  }



export const getAssignRoleToUserMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignRoleToUser>>, TError,{id: number;roleId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof assignRoleToUser>>, TError,{id: number;roleId: number}, TContext> => {

const mutationKey = ['assignRoleToUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignRoleToUser>>, {id: number;roleId: number}> = (props) => {
          const {id,roleId} = props ?? {};

          return  assignRoleToUser(id,roleId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AssignRoleToUserMutationResult = NonNullable<Awaited<ReturnType<typeof assignRoleToUser>>>
    
    export type AssignRoleToUserMutationError = AxiosError<ErrorVO>

    /**
 * @summary Assign role to user
 */
export const useAssignRoleToUser = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignRoleToUser>>, TError,{id: number;roleId: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof assignRoleToUser>>,
        TError,
        {id: number;roleId: number},
        TContext
      > => {

      const mutationOptions = getAssignRoleToUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Update the status of a user by their ID
 * @summary Update user status
 */
export const updateStatus = (
    id: number,
    params: UpdateStatusParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.patch(
      `/api/v1/users/${id}/status`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getUpdateStatusMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStatus>>, TError,{id: number;params: UpdateStatusParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateStatus>>, TError,{id: number;params: UpdateStatusParams}, TContext> => {

const mutationKey = ['updateStatus'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStatus>>, {id: number;params: UpdateStatusParams}> = (props) => {
          const {id,params} = props ?? {};

          return  updateStatus(id,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateStatus>>>
    
    export type UpdateStatusMutationError = AxiosError<ErrorVO>

    /**
 * @summary Update user status
 */
export const useUpdateStatus = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStatus>>, TError,{id: number;params: UpdateStatusParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateStatus>>,
        TError,
        {id: number;params: UpdateStatusParams},
        TContext
      > => {

      const mutationOptions = getUpdateStatusMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Retrieve a paginated list of all users
 * @summary Get all users
 */
export const getAllUsers = (
    params: GetAllUsersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PageVO>> => {
    
    
    return axios.default.get(
      `/api/v1/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAllUsersQueryKey = (params?: GetAllUsersParams,) => {
    return [
    `/api/v1/users`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllUsersQueryOptions = <TData = Awaited<ReturnType<typeof getAllUsers>>, TError = AxiosError<ErrorVO>>(params: GetAllUsersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllUsersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUsers>>> = ({ signal }) => getAllUsers(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllUsers>>>
export type GetAllUsersQueryError = AxiosError<ErrorVO>


/**
 * @summary Get all users
 */

export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = AxiosError<ErrorVO>>(
 params: GetAllUsersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllUsersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




