/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorVO,
  GetAllUsersParams,
  PageVO,
  UpdateStatusParams,
  UserRequestDTO,
  UserResponseDTO
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a user by their ID
 * @summary Get user by ID
 */
export const getUserById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<UserResponseDTO>(
      {url: `/api/v1/users/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetUserByIdQueryKey = (id?: number,) => {
    return [
    `/api/v1/users/${id}`
    ] as const;
    }

    
export const getGetUserByIdQueryOptions = <TData = Awaited<ReturnType<typeof getUserById>>, TError = ErrorType<ErrorVO>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserById>>> = ({ signal }) => getUserById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUserById>>>
export type GetUserByIdQueryError = ErrorType<ErrorVO>


export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = ErrorType<ErrorVO>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserById>>,
          TError,
          Awaited<ReturnType<typeof getUserById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = ErrorType<ErrorVO>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserById>>,
          TError,
          Awaited<ReturnType<typeof getUserById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = ErrorType<ErrorVO>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user by ID
 */

export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = ErrorType<ErrorVO>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing user by their ID
 * @summary Update user
 */
export const updateUser = (
    id: number,
    userRequestDTO: BodyType<UserRequestDTO>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      const formData = new FormData();
formData.append(`fullname`, userRequestDTO.fullname)
formData.append(`username`, userRequestDTO.username)
formData.append(`email`, userRequestDTO.email)
if(userRequestDTO.phone !== undefined) {
 formData.append(`phone`, userRequestDTO.phone)
 }
if(userRequestDTO.avatar !== undefined) {
 formData.append(`avatar`, userRequestDTO.avatar)
 }
formData.append(`roleId`, userRequestDTO.roleId.toString())

      return axiosInstanceFn<UserResponseDTO>(
      {url: `/api/v1/users/${id}`, method: 'PUT',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  


export const getUpdateUserMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: BodyType<UserRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: BodyType<UserRequestDTO>}, TContext> => {

const mutationKey = ['updateUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUser>>, {id: number;data: BodyType<UserRequestDTO>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateUser(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
    export type UpdateUserMutationBody = BodyType<UserRequestDTO>
    export type UpdateUserMutationError = ErrorType<ErrorVO>

    /**
 * @summary Update user
 */
export const useUpdateUser = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: BodyType<UserRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {id: number;data: BodyType<UserRequestDTO>},
        TContext
      > => {

      const mutationOptions = getUpdateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a user by their ID
 * @summary Delete user
 */
export const deleteUser = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<void>(
      {url: `/api/v1/users/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteUserMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteUser(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    
    export type DeleteUserMutationError = ErrorType<ErrorVO>

    /**
 * @summary Delete user
 */
export const useDeleteUser = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Assign a role to a user by their ID
 * @summary Assign role to user
 */
export const assignRoleToUser = (
    id: number,
    roleId: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<void>(
      {url: `/api/v1/users/${id}/assign-role/${roleId}`, method: 'POST', signal
    },
      options);
    }
  


export const getAssignRoleToUserMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignRoleToUser>>, TError,{id: number;roleId: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof assignRoleToUser>>, TError,{id: number;roleId: number}, TContext> => {

const mutationKey = ['assignRoleToUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignRoleToUser>>, {id: number;roleId: number}> = (props) => {
          const {id,roleId} = props ?? {};

          return  assignRoleToUser(id,roleId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AssignRoleToUserMutationResult = NonNullable<Awaited<ReturnType<typeof assignRoleToUser>>>
    
    export type AssignRoleToUserMutationError = ErrorType<ErrorVO>

    /**
 * @summary Assign role to user
 */
export const useAssignRoleToUser = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignRoleToUser>>, TError,{id: number;roleId: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assignRoleToUser>>,
        TError,
        {id: number;roleId: number},
        TContext
      > => {

      const mutationOptions = getAssignRoleToUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Update the status of a user by their ID
 * @summary Update user status
 */
export const updateStatus = (
    id: number,
    params: UpdateStatusParams,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<void>(
      {url: `/api/v1/users/${id}/status`, method: 'PATCH',
        params
    },
      options);
    }
  


export const getUpdateStatusMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStatus>>, TError,{id: number;params: UpdateStatusParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateStatus>>, TError,{id: number;params: UpdateStatusParams}, TContext> => {

const mutationKey = ['updateStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStatus>>, {id: number;params: UpdateStatusParams}> = (props) => {
          const {id,params} = props ?? {};

          return  updateStatus(id,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateStatus>>>
    
    export type UpdateStatusMutationError = ErrorType<ErrorVO>

    /**
 * @summary Update user status
 */
export const useUpdateStatus = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStatus>>, TError,{id: number;params: UpdateStatusParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStatus>>,
        TError,
        {id: number;params: UpdateStatusParams},
        TContext
      > => {

      const mutationOptions = getUpdateStatusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a paginated list of all users
 * @summary Get all users
 */
export const getAllUsers = (
    params: GetAllUsersParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<PageVO>(
      {url: `/api/v1/users`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllUsersQueryKey = (params?: GetAllUsersParams,) => {
    return [
    `/api/v1/users`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllUsersQueryOptions = <TData = Awaited<ReturnType<typeof getAllUsers>>, TError = ErrorType<ErrorVO>>(params: GetAllUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllUsersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUsers>>> = ({ signal }) => getAllUsers(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllUsers>>>
export type GetAllUsersQueryError = ErrorType<ErrorVO>


export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = ErrorType<ErrorVO>>(
 params: GetAllUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = ErrorType<ErrorVO>>(
 params: GetAllUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = ErrorType<ErrorVO>>(
 params: GetAllUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all users
 */

export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = ErrorType<ErrorVO>>(
 params: GetAllUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




