/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Retrieve a user by their ID
 * @summary Get user by ID
 */
export const getUserByIdParams = zod.object({
  "id": zod.number()
})

/**
 * Update an existing user by their ID
 * @summary Update user
 */
export const updateUserParams = zod.object({
  "id": zod.number()
})

export const updateUserBodyUsernameRegExp = new RegExp('^[a-zA-Z][a-zA-Z0-9]*$');
export const updateUserBodyPhoneRegExp = new RegExp('^(\\+84|0)(3[2-9]|5[2-9]|7[0|6-9]|8[1-9]|9[0-4|6-9])[0-9]{7}$');


export const updateUserBody = zod.object({
  "fullname": zod.string(),
  "username": zod.string().regex(updateUserBodyUsernameRegExp),
  "email": zod.string(),
  "phone": zod.string().regex(updateUserBodyPhoneRegExp).optional(),
  "avatar": zod.instanceof(File).optional(),
  "roleId": zod.number()
})

/**
 * Delete a user by their ID
 * @summary Delete user
 */
export const deleteUserParams = zod.object({
  "id": zod.number()
})

/**
 * Assign a role to a user by their ID
 * @summary Assign role to user
 */
export const assignRoleToUserParams = zod.object({
  "id": zod.number(),
  "roleId": zod.number()
})

/**
 * Update the status of a user by their ID
 * @summary Update user status
 */
export const updateStatusParams = zod.object({
  "id": zod.number()
})

export const updateStatusQueryParams = zod.object({
  "status": zod.string()
})

/**
 * Retrieve a paginated list of all users
 * @summary Get all users
 */
export const getAllUsersQueryPageDefault = 0;
export const getAllUsersQueryPageMin = 0;

export const getAllUsersQuerySizeDefault = 20;



export const getAllUsersQueryParams = zod.object({
  "page": zod.number().min(getAllUsersQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getAllUsersQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.object({

})
})

