/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Mark a specific notification as read by ID
 * @summary Mark a notification as read
 */
export const markAsReadParams = zod.object({
  "id": zod.number().describe('Notification ID to mark as read')
})

/**
 * Send a custom notification to multiple users
 * @summary Send a notification to users
 */
export const sendBody = zod.object({
  "userIds": zod.array(zod.number()).optional(),
  "type": zod.enum(['GENERAL', 'ORDER_PLACED', 'ORDER_RECEIVED', 'ORDER_PREPARING', 'ORDER_DELIVERING', 'ORDER_DELIVERED', 'ORDER_CANCELLED', 'ORDER_PAYMENT_SUCCEEDED', 'ORDER_PAYMENT_FAILED', 'PROMOTION']).optional(),
  "title": zod.string().optional(),
  "message": zod.string().optional()
})

/**
 * Send a notification to all users with role USER
 * @summary Send notification to all users
 */
export const sendToAllBody = zod.object({
  "userIds": zod.array(zod.number()).optional(),
  "type": zod.enum(['GENERAL', 'ORDER_PLACED', 'ORDER_RECEIVED', 'ORDER_PREPARING', 'ORDER_DELIVERING', 'ORDER_DELIVERED', 'ORDER_CANCELLED', 'ORDER_PAYMENT_SUCCEEDED', 'ORDER_PAYMENT_FAILED', 'PROMOTION']).optional(),
  "title": zod.string().optional(),
  "message": zod.string().optional()
})

/**
 * Admin only: Retrieve all notifications with filter
 * @summary Get all notifications (Admin)
 */
export const getAllNotificationsQueryPageDefault = 0;
export const getAllNotificationsQueryPageMin = 0;

export const getAllNotificationsQuerySizeDefault = 20;



export const getAllNotificationsQueryParams = zod.object({
  "page": zod.number().min(getAllNotificationsQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getAllNotificationsQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.object({

})
})

/**
 * Get paginated and filtered notifications for the current user
 * @summary Get my notifications
 */
export const getMyNotificationsQueryPageDefault = 0;
export const getMyNotificationsQueryPageMin = 0;

export const getMyNotificationsQuerySizeDefault = 20;



export const getMyNotificationsQueryParams = zod.object({
  "page": zod.number().min(getMyNotificationsQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getMyNotificationsQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.object({

})
})

/**
 * Delete a notification by ID
 * @summary Delete a notification
 */
export const delete2Params = zod.object({
  "id": zod.number().describe('Notification ID to delete')
})

