/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CartItemRequestDTO,
  CartItemResponseDTO,
  ErrorVO,
  GetAllCartItemsParams,
  PageVO
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Update an existing cart item by ID
 * @summary Update a cart item
 */
export const updateCartItem = (
    id: number,
    cartItemRequestDTO: BodyType<CartItemRequestDTO>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<CartItemResponseDTO>(
      {url: `/api/v1/cart-items/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: cartItemRequestDTO
    },
      options);
    }
  


export const getUpdateCartItemMutationOptions = <TError = ErrorType<ErrorVO | CartItemResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCartItem>>, TError,{id: number;data: BodyType<CartItemRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCartItem>>, TError,{id: number;data: BodyType<CartItemRequestDTO>}, TContext> => {

const mutationKey = ['updateCartItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCartItem>>, {id: number;data: BodyType<CartItemRequestDTO>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCartItem(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCartItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateCartItem>>>
    export type UpdateCartItemMutationBody = BodyType<CartItemRequestDTO>
    export type UpdateCartItemMutationError = ErrorType<ErrorVO | CartItemResponseDTO>

    /**
 * @summary Update a cart item
 */
export const useUpdateCartItem = <TError = ErrorType<ErrorVO | CartItemResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCartItem>>, TError,{id: number;data: BodyType<CartItemRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCartItem>>,
        TError,
        {id: number;data: BodyType<CartItemRequestDTO>},
        TContext
      > => {

      const mutationOptions = getUpdateCartItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Remove a cart item by its ID
 * @summary Delete a cart item
 */
export const deleteCartItem = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<void>(
      {url: `/api/v1/cart-items/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteCartItemMutationOptions = <TError = ErrorType<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCartItem>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCartItem>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCartItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCartItem>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCartItem(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCartItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCartItem>>>
    
    export type DeleteCartItemMutationError = ErrorType<ErrorVO | void>

    /**
 * @summary Delete a cart item
 */
export const useDeleteCartItem = <TError = ErrorType<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCartItem>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCartItem>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteCartItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve all cart items with optional pagination
 * @summary Get all cart items
 */
export const getAllCartItems = (
    params?: GetAllCartItemsParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<PageVO>(
      {url: `/api/v1/cart-items`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllCartItemsQueryKey = (params?: GetAllCartItemsParams,) => {
    return [
    `/api/v1/cart-items`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllCartItemsQueryOptions = <TData = Awaited<ReturnType<typeof getAllCartItems>>, TError = ErrorType<ErrorVO>>(params?: GetAllCartItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCartItems>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllCartItemsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllCartItems>>> = ({ signal }) => getAllCartItems(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllCartItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllCartItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllCartItems>>>
export type GetAllCartItemsQueryError = ErrorType<ErrorVO>


export function useGetAllCartItems<TData = Awaited<ReturnType<typeof getAllCartItems>>, TError = ErrorType<ErrorVO>>(
 params: undefined |  GetAllCartItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCartItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCartItems>>,
          TError,
          Awaited<ReturnType<typeof getAllCartItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllCartItems<TData = Awaited<ReturnType<typeof getAllCartItems>>, TError = ErrorType<ErrorVO>>(
 params?: GetAllCartItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCartItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCartItems>>,
          TError,
          Awaited<ReturnType<typeof getAllCartItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllCartItems<TData = Awaited<ReturnType<typeof getAllCartItems>>, TError = ErrorType<ErrorVO>>(
 params?: GetAllCartItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCartItems>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all cart items
 */

export function useGetAllCartItems<TData = Awaited<ReturnType<typeof getAllCartItems>>, TError = ErrorType<ErrorVO>>(
 params?: GetAllCartItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCartItems>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllCartItemsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Add a new item to the cart
 * @summary Create a cart item
 */
export const createCartItem = (
    cartItemRequestDTO: BodyType<CartItemRequestDTO>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<CartItemResponseDTO>(
      {url: `/api/v1/cart-items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cartItemRequestDTO, signal
    },
      options);
    }
  


export const getCreateCartItemMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCartItem>>, TError,{data: BodyType<CartItemRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createCartItem>>, TError,{data: BodyType<CartItemRequestDTO>}, TContext> => {

const mutationKey = ['createCartItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCartItem>>, {data: BodyType<CartItemRequestDTO>}> = (props) => {
          const {data} = props ?? {};

          return  createCartItem(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCartItemMutationResult = NonNullable<Awaited<ReturnType<typeof createCartItem>>>
    export type CreateCartItemMutationBody = BodyType<CartItemRequestDTO>
    export type CreateCartItemMutationError = ErrorType<ErrorVO>

    /**
 * @summary Create a cart item
 */
export const useCreateCartItem = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCartItem>>, TError,{data: BodyType<CartItemRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCartItem>>,
        TError,
        {data: BodyType<CartItemRequestDTO>},
        TContext
      > => {

      const mutationOptions = getCreateCartItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    