/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Update an existing cart item by ID
 * @summary Update a cart item
 */
export const updateCartItemParams = zod.object({
  "id": zod.number().describe('ID of the cart item to update')
})

export const updateCartItemBody = zod.object({
  "productId": zod.number().optional(),
  "quantity": zod.number().optional(),
  "variationOptionIds": zod.array(zod.number()).optional()
}).describe('Cart item data')

/**
 * Remove a cart item by its ID
 * @summary Delete a cart item
 */
export const deleteCartItemParams = zod.object({
  "id": zod.number().describe('ID of the cart item to delete')
})

/**
 * Retrieve all cart items with optional pagination
 * @summary Get all cart items
 */
export const getAllCartItemsQueryPageDefault = 0;
export const getAllCartItemsQueryPageMin = 0;

export const getAllCartItemsQuerySizeDefault = 20;



export const getAllCartItemsQueryParams = zod.object({
  "page": zod.number().min(getAllCartItemsQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getAllCartItemsQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.')
})

/**
 * Add a new item to the cart
 * @summary Create a cart item
 */
export const createCartItemBody = zod.object({
  "productId": zod.number().optional(),
  "quantity": zod.number().optional(),
  "variationOptionIds": zod.array(zod.number()).optional()
}).describe('Cart item data')

