/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CartItemRequestDTO,
  CartItemResponseDTO,
  ErrorVO,
  GetAllCartItemsParams,
  PageVO
} from '../../types';





/**
 * Update an existing cart item by ID
 * @summary Update a cart item
 */
export const updateCartItem = (
    id: number,
    cartItemRequestDTO: CartItemRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CartItemResponseDTO>> => {
    
    
    return axios.default.put(
      `/api/v1/cart-items/${id}`,
      cartItemRequestDTO,options
    );
  }



export const getUpdateCartItemMutationOptions = <TError = AxiosError<ErrorVO | CartItemResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCartItem>>, TError,{id: number;data: CartItemRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateCartItem>>, TError,{id: number;data: CartItemRequestDTO}, TContext> => {

const mutationKey = ['updateCartItem'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCartItem>>, {id: number;data: CartItemRequestDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCartItem(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCartItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateCartItem>>>
    export type UpdateCartItemMutationBody = CartItemRequestDTO
    export type UpdateCartItemMutationError = AxiosError<ErrorVO | CartItemResponseDTO>

    /**
 * @summary Update a cart item
 */
export const useUpdateCartItem = <TError = AxiosError<ErrorVO | CartItemResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCartItem>>, TError,{id: number;data: CartItemRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateCartItem>>,
        TError,
        {id: number;data: CartItemRequestDTO},
        TContext
      > => {

      const mutationOptions = getUpdateCartItemMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Remove a cart item by its ID
 * @summary Delete a cart item
 */
export const deleteCartItem = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/v1/cart-items/${id}`,options
    );
  }



export const getDeleteCartItemMutationOptions = <TError = AxiosError<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCartItem>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCartItem>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCartItem'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCartItem>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCartItem(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCartItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCartItem>>>
    
    export type DeleteCartItemMutationError = AxiosError<ErrorVO | void>

    /**
 * @summary Delete a cart item
 */
export const useDeleteCartItem = <TError = AxiosError<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCartItem>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteCartItem>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteCartItemMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Retrieve all cart items with optional pagination
 * @summary Get all cart items
 */
export const getAllCartItems = (
    params?: GetAllCartItemsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PageVO>> => {
    
    
    return axios.default.get(
      `/api/v1/cart-items`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAllCartItemsQueryKey = (params?: GetAllCartItemsParams,) => {
    return [
    `/api/v1/cart-items`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllCartItemsQueryOptions = <TData = Awaited<ReturnType<typeof getAllCartItems>>, TError = AxiosError<ErrorVO>>(params?: GetAllCartItemsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllCartItems>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllCartItemsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllCartItems>>> = ({ signal }) => getAllCartItems(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllCartItems>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllCartItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllCartItems>>>
export type GetAllCartItemsQueryError = AxiosError<ErrorVO>


/**
 * @summary Get all cart items
 */

export function useGetAllCartItems<TData = Awaited<ReturnType<typeof getAllCartItems>>, TError = AxiosError<ErrorVO>>(
 params?: GetAllCartItemsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllCartItems>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllCartItemsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Add a new item to the cart
 * @summary Create a cart item
 */
export const createCartItem = (
    cartItemRequestDTO: CartItemRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CartItemResponseDTO>> => {
    
    
    return axios.default.post(
      `/api/v1/cart-items`,
      cartItemRequestDTO,options
    );
  }



export const getCreateCartItemMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCartItem>>, TError,{data: CartItemRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createCartItem>>, TError,{data: CartItemRequestDTO}, TContext> => {

const mutationKey = ['createCartItem'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCartItem>>, {data: CartItemRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  createCartItem(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCartItemMutationResult = NonNullable<Awaited<ReturnType<typeof createCartItem>>>
    export type CreateCartItemMutationBody = CartItemRequestDTO
    export type CreateCartItemMutationError = AxiosError<ErrorVO>

    /**
 * @summary Create a cart item
 */
export const useCreateCartItem = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCartItem>>, TError,{data: CartItemRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createCartItem>>,
        TError,
        {data: CartItemRequestDTO},
        TContext
      > => {

      const mutationOptions = getCreateCartItemMutationOptions(options);

      return useMutation(mutationOptions);
    }
    