/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorVO,
  GetByVariationIdParams,
  PageVO,
  VariationOptionRequestDTO,
  VariationOptionResponseDTO
} from '../../types';





/**
 * Update an existing variation option by its ID (Admin only)
 * @summary Update a variation option
 */
export const update = (
    id: number,
    variationOptionRequestDTO: VariationOptionRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VariationOptionResponseDTO>> => {
    
    
    return axios.default.put(
      `/api/v1/variation-options/${id}`,
      variationOptionRequestDTO,options
    );
  }



export const getUpdateMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update>>, TError,{id: number;data: VariationOptionRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof update>>, TError,{id: number;data: VariationOptionRequestDTO}, TContext> => {

const mutationKey = ['update'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof update>>, {id: number;data: VariationOptionRequestDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  update(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMutationResult = NonNullable<Awaited<ReturnType<typeof update>>>
    export type UpdateMutationBody = VariationOptionRequestDTO
    export type UpdateMutationError = AxiosError<ErrorVO>

    /**
 * @summary Update a variation option
 */
export const useUpdate = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update>>, TError,{id: number;data: VariationOptionRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof update>>,
        TError,
        {id: number;data: VariationOptionRequestDTO},
        TContext
      > => {

      const mutationOptions = getUpdateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Delete a variation option by its ID (Admin only)
 * @summary Delete a variation option
 */
export const _delete = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/v1/variation-options/${id}`,options
    );
  }



export const getDeleteMutationOptions = <TError = AxiosError<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError,{id: number}, TContext> => {

const mutationKey = ['_delete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof _delete>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  _delete(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type _DeleteMutationResult = NonNullable<Awaited<ReturnType<typeof _delete>>>
    
    export type _DeleteMutationError = AxiosError<ErrorVO | void>

    /**
 * @summary Delete a variation option
 */
export const useDelete = <TError = AxiosError<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof _delete>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Retrieve all variation options associated with a specific variation
 * @summary Get variation options by variation ID
 */
export const getByVariationId = (
    params: GetByVariationIdParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PageVO>> => {
    
    
    return axios.default.get(
      `/api/v1/variation-options`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetByVariationIdQueryKey = (params?: GetByVariationIdParams,) => {
    return [
    `/api/v1/variation-options`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetByVariationIdQueryOptions = <TData = Awaited<ReturnType<typeof getByVariationId>>, TError = AxiosError<ErrorVO>>(params: GetByVariationIdParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getByVariationId>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetByVariationIdQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getByVariationId>>> = ({ signal }) => getByVariationId(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getByVariationId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetByVariationIdQueryResult = NonNullable<Awaited<ReturnType<typeof getByVariationId>>>
export type GetByVariationIdQueryError = AxiosError<ErrorVO>


/**
 * @summary Get variation options by variation ID
 */

export function useGetByVariationId<TData = Awaited<ReturnType<typeof getByVariationId>>, TError = AxiosError<ErrorVO>>(
 params: GetByVariationIdParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getByVariationId>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetByVariationIdQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new variation option (Admin only)
 * @summary Create a variation option
 */
export const create = (
    variationOptionRequestDTO: VariationOptionRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VariationOptionResponseDTO>> => {
    
    
    return axios.default.post(
      `/api/v1/variation-options`,
      variationOptionRequestDTO,options
    );
  }



export const getCreateMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: VariationOptionRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: VariationOptionRequestDTO}, TContext> => {

const mutationKey = ['create'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof create>>, {data: VariationOptionRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  create(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMutationResult = NonNullable<Awaited<ReturnType<typeof create>>>
    export type CreateMutationBody = VariationOptionRequestDTO
    export type CreateMutationError = AxiosError<ErrorVO>

    /**
 * @summary Create a variation option
 */
export const useCreate = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: VariationOptionRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof create>>,
        TError,
        {data: VariationOptionRequestDTO},
        TContext
      > => {

      const mutationOptions = getCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    