/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorVO,
  GetByVariationIdParams,
  PageVO,
  VariationOptionRequestDTO,
  VariationOptionResponseDTO
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Update an existing variation option by its ID (Admin only)
 * @summary Update a variation option
 */
export const update = (
    id: number,
    variationOptionRequestDTO: BodyType<VariationOptionRequestDTO>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<VariationOptionResponseDTO>(
      {url: `/api/v1/variation-options/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: variationOptionRequestDTO
    },
      options);
    }
  


export const getUpdateMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update>>, TError,{id: number;data: BodyType<VariationOptionRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof update>>, TError,{id: number;data: BodyType<VariationOptionRequestDTO>}, TContext> => {

const mutationKey = ['update'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof update>>, {id: number;data: BodyType<VariationOptionRequestDTO>}> = (props) => {
          const {id,data} = props ?? {};

          return  update(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMutationResult = NonNullable<Awaited<ReturnType<typeof update>>>
    export type UpdateMutationBody = BodyType<VariationOptionRequestDTO>
    export type UpdateMutationError = ErrorType<ErrorVO>

    /**
 * @summary Update a variation option
 */
export const useUpdate = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update>>, TError,{id: number;data: BodyType<VariationOptionRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof update>>,
        TError,
        {id: number;data: BodyType<VariationOptionRequestDTO>},
        TContext
      > => {

      const mutationOptions = getUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a variation option by its ID (Admin only)
 * @summary Delete a variation option
 */
export const _delete = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<void>(
      {url: `/api/v1/variation-options/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteMutationOptions = <TError = ErrorType<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError,{id: number}, TContext> => {

const mutationKey = ['_delete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof _delete>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  _delete(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type _DeleteMutationResult = NonNullable<Awaited<ReturnType<typeof _delete>>>
    
    export type _DeleteMutationError = ErrorType<ErrorVO | void>

    /**
 * @summary Delete a variation option
 */
export const useDelete = <TError = ErrorType<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof _delete>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve all variation options associated with a specific variation
 * @summary Get variation options by variation ID
 */
export const getByVariationId = (
    params: GetByVariationIdParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<PageVO>(
      {url: `/api/v1/variation-options`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetByVariationIdQueryKey = (params?: GetByVariationIdParams,) => {
    return [
    `/api/v1/variation-options`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetByVariationIdQueryOptions = <TData = Awaited<ReturnType<typeof getByVariationId>>, TError = ErrorType<ErrorVO>>(params: GetByVariationIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByVariationId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetByVariationIdQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getByVariationId>>> = ({ signal }) => getByVariationId(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getByVariationId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetByVariationIdQueryResult = NonNullable<Awaited<ReturnType<typeof getByVariationId>>>
export type GetByVariationIdQueryError = ErrorType<ErrorVO>


export function useGetByVariationId<TData = Awaited<ReturnType<typeof getByVariationId>>, TError = ErrorType<ErrorVO>>(
 params: GetByVariationIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByVariationId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getByVariationId>>,
          TError,
          Awaited<ReturnType<typeof getByVariationId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetByVariationId<TData = Awaited<ReturnType<typeof getByVariationId>>, TError = ErrorType<ErrorVO>>(
 params: GetByVariationIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByVariationId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getByVariationId>>,
          TError,
          Awaited<ReturnType<typeof getByVariationId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetByVariationId<TData = Awaited<ReturnType<typeof getByVariationId>>, TError = ErrorType<ErrorVO>>(
 params: GetByVariationIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByVariationId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get variation options by variation ID
 */

export function useGetByVariationId<TData = Awaited<ReturnType<typeof getByVariationId>>, TError = ErrorType<ErrorVO>>(
 params: GetByVariationIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByVariationId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetByVariationIdQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new variation option (Admin only)
 * @summary Create a variation option
 */
export const create = (
    variationOptionRequestDTO: BodyType<VariationOptionRequestDTO>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<VariationOptionResponseDTO>(
      {url: `/api/v1/variation-options`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: variationOptionRequestDTO, signal
    },
      options);
    }
  


export const getCreateMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: BodyType<VariationOptionRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: BodyType<VariationOptionRequestDTO>}, TContext> => {

const mutationKey = ['create'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof create>>, {data: BodyType<VariationOptionRequestDTO>}> = (props) => {
          const {data} = props ?? {};

          return  create(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMutationResult = NonNullable<Awaited<ReturnType<typeof create>>>
    export type CreateMutationBody = BodyType<VariationOptionRequestDTO>
    export type CreateMutationError = ErrorType<ErrorVO>

    /**
 * @summary Create a variation option
 */
export const useCreate = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: BodyType<VariationOptionRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof create>>,
        TError,
        {data: BodyType<VariationOptionRequestDTO>},
        TContext
      > => {

      const mutationOptions = getCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    