/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Update an existing variation option by its ID (Admin only)
 * @summary Update a variation option
 */
export const updateParams = zod.object({
  "id": zod.number().describe('ID of the variation option to update')
})

export const updateBody = zod.object({
  "value": zod.string(),
  "additionalPrice": zod.number(),
  "variationId": zod.number()
})

/**
 * Delete a variation option by its ID (Admin only)
 * @summary Delete a variation option
 */
export const _deleteParams = zod.object({
  "id": zod.number().describe('ID of the variation option to delete')
})

/**
 * Retrieve all variation options associated with a specific variation
 * @summary Get variation options by variation ID
 */
export const getByVariationIdQueryPageDefault = 0;
export const getByVariationIdQueryPageMin = 0;

export const getByVariationIdQuerySizeDefault = 20;



export const getByVariationIdQueryParams = zod.object({
  "arg0": zod.number().describe('ID of the variation'),
  "page": zod.number().min(getByVariationIdQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getByVariationIdQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.')
})

/**
 * Create a new variation option (Admin only)
 * @summary Create a variation option
 */
export const createBody = zod.object({
  "value": zod.string(),
  "additionalPrice": zod.number(),
  "variationId": zod.number()
})

