/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { ApplicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItemAnnotationsItem } from './applicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItemAnnotationsItem';
import type { ApplicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItemDeclaredAnnotationsItem } from './applicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItemDeclaredAnnotationsItem';

export type ApplicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItem = {
  name?: string;
  sealed?: boolean;
  annotations?: ApplicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItemAnnotationsItem[];
  declaredAnnotations?: ApplicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItemDeclaredAnnotationsItem[];
  specificationTitle?: string;
  specificationVersion?: string;
  specificationVendor?: string;
  implementationTitle?: string;
  implementationVersion?: string;
  implementationVendor?: string;
};
