/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { ApplicationContext as __ApplicationContext } from './applicationContext';
import type { AutowireCapableBeanFactory } from './autowireCapableBeanFactory';
import type { Environment } from './environment';
import type { BeanFactory } from './beanFactory';
import type { ApplicationContextClassLoader } from './applicationContextClassLoader';

export interface ApplicationContext {
  parent?: __ApplicationContext;
  id?: string;
  displayName?: string;
  autowireCapableBeanFactory?: AutowireCapableBeanFactory;
  applicationName?: string;
  startupDate?: number;
  environment?: Environment;
  beanDefinitionCount?: number;
  beanDefinitionNames?: string[];
  parentBeanFactory?: BeanFactory;
  classLoader?: ApplicationContextClassLoader;
}
