/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { ApplicationContextClassLoaderUnnamedModuleClassLoader } from './applicationContextClassLoaderUnnamedModuleClassLoader';
import type { ApplicationContextClassLoaderUnnamedModuleDescriptor } from './applicationContextClassLoaderUnnamedModuleDescriptor';
import type { ApplicationContextClassLoaderUnnamedModuleAnnotationsItem } from './applicationContextClassLoaderUnnamedModuleAnnotationsItem';
import type { ApplicationContextClassLoaderUnnamedModuleDeclaredAnnotationsItem } from './applicationContextClassLoaderUnnamedModuleDeclaredAnnotationsItem';
import type { ApplicationContextClassLoaderUnnamedModuleLayer } from './applicationContextClassLoaderUnnamedModuleLayer';

export type ApplicationContextClassLoaderUnnamedModule = {
  name?: string;
  classLoader?: ApplicationContextClassLoaderUnnamedModuleClassLoader;
  descriptor?: ApplicationContextClassLoaderUnnamedModuleDescriptor;
  named?: boolean;
  annotations?: ApplicationContextClassLoaderUnnamedModuleAnnotationsItem[];
  declaredAnnotations?: ApplicationContextClassLoaderUnnamedModuleDeclaredAnnotationsItem[];
  packages?: string[];
  nativeAccessEnabled?: boolean;
  layer?: ApplicationContextClassLoaderUnnamedModuleLayer;
};
