/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesItemAnnotationsItem } from './applicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesItemAnnotationsItem';
import type { ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesItemDeclaredAnnotationsItem } from './applicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesItemDeclaredAnnotationsItem';

export type ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesItem = {
  name?: string;
  sealed?: boolean;
  annotations?: ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesItemAnnotationsItem[];
  declaredAnnotations?: ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesItemDeclaredAnnotationsItem[];
  specificationTitle?: string;
  specificationVersion?: string;
  specificationVendor?: string;
  implementationTitle?: string;
  implementationVersion?: string;
  implementationVendor?: string;
};
