/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { ApplicationContextClassLoaderParent } from './applicationContextClassLoaderParent';
import type { ApplicationContextClassLoaderUnnamedModule } from './applicationContextClassLoaderUnnamedModule';
import type { ApplicationContextClassLoaderDefinedPackagesItem } from './applicationContextClassLoaderDefinedPackagesItem';

export type ApplicationContextClassLoader = {
  name?: string;
  registeredAsParallelCapable?: boolean;
  parent?: ApplicationContextClassLoaderParent;
  unnamedModule?: ApplicationContextClassLoaderUnnamedModule;
  definedPackages?: ApplicationContextClassLoaderDefinedPackagesItem[];
  defaultAssertionStatus?: boolean;
};
