/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */

export interface CartItemResponseDTO {
  id?: number;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: number;
  updatedBy?: number;
  cartId?: number;
  quantity?: number;
  price?: number;
  productId?: number;
  productName?: string;
  variationOptionIds?: number[];
  imageUrl?: string;
  available?: boolean;
  variationOptionInfo?: string;
}
