/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { CartItemResponseDTO } from './cartItemResponseDTO';

export interface CartResponseDTO {
  id?: number;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: number;
  updatedBy?: number;
  userId?: number;
  cartItems?: CartItemResponseDTO[];
}
