/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */

export type ErrorVOType = typeof ErrorVOType[keyof typeof ErrorVOType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorVOType = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_FIELD_ERROR: 'MISSING_FIELD_ERROR',
  INVALID_INPUT_ERROR: 'INVALID_INPUT_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  RESOURCE_NOT_FOUND_ERROR: 'RESOURCE_NOT_FOUND_ERROR',
  RESOURCE_CONFLICT_ERROR: 'RESOURCE_CONFLICT_ERROR',
  RESOURCE_GONE_ERROR: 'RESOURCE_GONE_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',
  BAD_REQUEST_ERROR: 'BAD_REQUEST_ERROR',
} as const;
