/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { FilterRegistrationInitParameters } from './filterRegistrationInitParameters';

export interface FilterRegistration {
  servletNameMappings?: string[];
  urlPatternMappings?: string[];
  initParameters?: FilterRegistrationInitParameters;
  name?: string;
  className?: string;
}
