/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { SpecificationShipper } from './specificationShipper';

export type GetAllParams = {
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
filter: SpecificationShipper;
};
