/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */

export interface JspPropertyGroupDescriptor {
  deferredSyntaxAllowedAsLiteral?: string;
  elIgnored?: string;
  errorOnELNotFound?: string;
  pageEncoding?: string;
  scriptingInvalid?: string;
  isXml?: string;
  includePreludes?: string[];
  includeCodas?: string[];
  trimDirectiveWhitespaces?: string;
  errorOnUndeclaredNamespace?: string;
  defaultContentType?: string;
  urlPatterns?: string[];
  buffer?: string;
}
