/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */

export type NotificationResponseDTOType = typeof NotificationResponseDTOType[keyof typeof NotificationResponseDTOType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationResponseDTOType = {
  GENERAL: 'GENERAL',
  ORDER_PLACED: 'ORDER_PLACED',
  ORDER_RECEIVED: 'ORDER_RECEIVED',
  ORDER_PREPARING: 'ORDER_PREPARING',
  ORDER_DELIVERING: 'ORDER_DELIVERING',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_PAYMENT_SUCCEEDED: 'ORDER_PAYMENT_SUCCEEDED',
  ORDER_PAYMENT_FAILED: 'ORDER_PAYMENT_FAILED',
  PROMOTION: 'PROMOTION',
} as const;
