/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */

export type OrderResponseDTOPaymentMethod = typeof OrderResponseDTOPaymentMethod[keyof typeof OrderResponseDTOPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderResponseDTOPaymentMethod = {
  CASH_ON_DELIVERY: 'CASH_ON_DELIVERY',
  VNPAY: 'VNPAY',
} as const;
