/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { OrderResponseDTOOrderStatus } from './orderResponseDTOOrderStatus';
import type { OrderResponseDTOPaymentMethod } from './orderResponseDTOPaymentMethod';
import type { OrderResponseDTOPaymentStatus } from './orderResponseDTOPaymentStatus';
import type { OrderDetailResponseDTO } from './orderDetailResponseDTO';

export interface OrderResponseDTO {
  id?: number;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: number;
  updatedBy?: number;
  destinationLatitude?: number;
  destinationLongitude?: number;
  shippingAddress?: string;
  totalPrice?: number;
  note?: string;
  expectedDeliveryTime?: string;
  actualDeliveryTime?: string;
  orderStatus?: OrderResponseDTOOrderStatus;
  userId?: number;
  shipperId?: number;
  paymentMethod?: OrderResponseDTOPaymentMethod;
  paymentStatus?: OrderResponseDTOPaymentStatus;
  txnRef?: string;
  orderDetails?: OrderDetailResponseDTO[];
}
