/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */

export type OrderResponseDTOOrderStatus = typeof OrderResponseDTOOrderStatus[keyof typeof OrderResponseDTOOrderStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderResponseDTOOrderStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  SHIPPING: 'SHIPPING',
  COMPLETED: 'COMPLETED',
  CANCELED: 'CANCELED',
} as const;
