/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */

export type OrderResponseDTOPaymentStatus = typeof OrderResponseDTOPaymentStatus[keyof typeof OrderResponseDTOPaymentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderResponseDTOPaymentStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELED: 'CANCELED',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ALREADY_CONFIRMED: 'ALREADY_CONFIRMED',
  INVALID_CHECKSUM: 'INVALID_CHECKSUM',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;
