/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { ProductCategory } from './productCategory';
import type { Variation } from './variation';
import type { CartItem } from './cartItem';

export interface Product {
  readonly id?: number;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  readonly createdBy?: number;
  readonly updatedBy?: number;
  category?: ProductCategory;
  variations?: Variation[];
  name: string;
  shortDescription?: string;
  detailDescription?: string;
  originalPrice: number;
  imageUrl?: string;
  isAvailable: boolean;
  deleted?: boolean;
  cartItems?: CartItem[];
}
