/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */

export interface ProductRequestDTO {
  categoryId?: number;
  name?: string;
  shortDescription?: string;
  detailDescription?: string;
  originalPrice?: number;
  image?: Blob;
}
