/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */

export interface PromotionResponseDTO {
  id?: number;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: number;
  updatedBy?: number;
  description?: string;
  discountValue?: number;
  minValue?: number;
  startDate?: string;
  endDate?: string;
  code?: string;
  isPublic?: boolean;
}
