/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { ServletContextInitParameterNames } from './servletContextInitParameterNames';
import type { ServletContextServletRegistrations } from './servletContextServletRegistrations';
import type { ServletContextFilterRegistrations } from './servletContextFilterRegistrations';
import type { SessionCookieConfig } from './sessionCookieConfig';
import type { ServletContextSessionTrackingModesItem } from './servletContextSessionTrackingModesItem';
import type { ServletContextDefaultSessionTrackingModesItem } from './servletContextDefaultSessionTrackingModesItem';
import type { ServletContextEffectiveSessionTrackingModesItem } from './servletContextEffectiveSessionTrackingModesItem';
import type { JspConfigDescriptor } from './jspConfigDescriptor';
import type { ServletContextClassLoader } from './servletContextClassLoader';
import type { ServletContextAttributeNames } from './servletContextAttributeNames';

export interface ServletContext {
  contextPath?: string;
  initParameterNames?: ServletContextInitParameterNames;
  effectiveMajorVersion?: number;
  effectiveMinorVersion?: number;
  serverInfo?: string;
  servletContextName?: string;
  servletRegistrations?: ServletContextServletRegistrations;
  filterRegistrations?: ServletContextFilterRegistrations;
  sessionCookieConfig?: SessionCookieConfig;
  sessionTrackingModes?: ServletContextSessionTrackingModesItem[];
  defaultSessionTrackingModes?: ServletContextDefaultSessionTrackingModesItem[];
  effectiveSessionTrackingModes?: ServletContextEffectiveSessionTrackingModesItem[];
  jspConfigDescriptor?: JspConfigDescriptor;
  virtualServerName?: string;
  sessionTimeout?: number;
  requestCharacterEncoding?: string;
  responseCharacterEncoding?: string;
  classLoader?: ServletContextClassLoader;
  majorVersion?: number;
  minorVersion?: number;
  attributeNames?: ServletContextAttributeNames;
}
