/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { ServletRegistrationInitParameters } from './servletRegistrationInitParameters';

export interface ServletRegistration {
  mappings?: string[];
  runAsRole?: string;
  initParameters?: ServletRegistrationInitParameters;
  name?: string;
  className?: string;
}
