/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { ServletContextClassLoaderDefinedPackagesItem } from './servletContextClassLoaderDefinedPackagesItem';

export type ServletContextClassLoader = {
  name?: string;
  registeredAsParallelCapable?: boolean;
  definedPackages?: ServletContextClassLoaderDefinedPackagesItem[];
  defaultAssertionStatus?: boolean;
};
