/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { UserResponseDTOStatus } from './userResponseDTOStatus';
import type { RoleResponseDTO } from './roleResponseDTO';

export interface UserResponseDTO {
  id?: number;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: number;
  updatedBy?: number;
  fullname?: string;
  username?: string;
  email?: string;
  phone?: string;
  avatarUrl?: string;
  status?: UserResponseDTOStatus;
  role?: RoleResponseDTO;
}
