/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */

export type UserResponseDTOStatus = typeof UserResponseDTOStatus[keyof typeof UserResponseDTOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseDTOStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETED: 'DELETED',
  BLOCKED: 'BLOCKED',
} as const;
