/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import type { Product } from './product';
import type { VariationOption } from './variationOption';

export interface Variation {
  readonly id?: number;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  readonly createdBy?: number;
  readonly updatedBy?: number;
  product?: Product;
  name: string;
  variationOptions?: VariationOption[];
  isMultipleChoice?: boolean;
}
