/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */

export interface VnPayRequestDTO {
  orderId?: number;
  orderInfo?: string;
  orderType?: string;
  bankCode?: string;
  language?: string;
  billingMobile?: string;
  billingEmail?: string;
  billingFullname?: string;
  billingAddress?: string;
  billingCity?: string;
  billingCountry?: string;
  billingState?: string;
  invMobile?: string;
  invEmail?: string;
  invCustomer?: string;
  invAddress?: string;
  invCompany?: string;
  invTaxCode?: string;
  invType?: string;
  returnUrl?: string;
}
