/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorVO,
  RedirectView,
  VnPayRequestDTO
} from '../../types';





/**
 * Generate a payment URL for VnPay
 * @summary Create VnPay payment
 */
export const createPayment = (
    vnPayRequestDTO: VnPayRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.post(
      `/api/v1/payment/create-payment`,
      vnPayRequestDTO,{
    ...options,}
    );
  }



export const getCreatePaymentMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPayment>>, TError,{data: VnPayRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createPayment>>, TError,{data: VnPayRequestDTO}, TContext> => {

const mutationKey = ['createPayment'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPayment>>, {data: VnPayRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  createPayment(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePaymentMutationResult = NonNullable<Awaited<ReturnType<typeof createPayment>>>
    export type CreatePaymentMutationBody = VnPayRequestDTO
    export type CreatePaymentMutationError = AxiosError<ErrorVO>

    /**
 * @summary Create VnPay payment
 */
export const useCreatePayment = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPayment>>, TError,{data: VnPayRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createPayment>>,
        TError,
        {data: VnPayRequestDTO},
        TContext
      > => {

      const mutationOptions = getCreatePaymentMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Handle return callback from VnPay after user completes payment
 * @summary Handle VNPAY return
 */
export const handleReturn = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.get(
      `/api/v1/payment/return`,{
    ...options,}
    );
  }




export const getHandleReturnQueryKey = () => {
    return [
    `/api/v1/payment/return`
    ] as const;
    }

    
export const getHandleReturnQueryOptions = <TData = Awaited<ReturnType<typeof handleReturn>>, TError = AxiosError<ErrorVO | RedirectView>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof handleReturn>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHandleReturnQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof handleReturn>>> = ({ signal }) => handleReturn({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof handleReturn>>, TError, TData> & { queryKey: QueryKey }
}

export type HandleReturnQueryResult = NonNullable<Awaited<ReturnType<typeof handleReturn>>>
export type HandleReturnQueryError = AxiosError<ErrorVO | RedirectView>


/**
 * @summary Handle VNPAY return
 */

export function useHandleReturn<TData = Awaited<ReturnType<typeof handleReturn>>, TError = AxiosError<ErrorVO | RedirectView>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof handleReturn>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHandleReturnQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




