/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorVO,
  RedirectView,
  VnPayRequestDTO
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Generate a payment URL for VnPay
 * @summary Create VnPay payment
 */
export const createPayment = (
    vnPayRequestDTO: BodyType<VnPayRequestDTO>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<string>(
      {url: `/api/v1/payment/create-payment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: vnPayRequestDTO, signal
    },
      options);
    }
  


export const getCreatePaymentMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPayment>>, TError,{data: BodyType<VnPayRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createPayment>>, TError,{data: BodyType<VnPayRequestDTO>}, TContext> => {

const mutationKey = ['createPayment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPayment>>, {data: BodyType<VnPayRequestDTO>}> = (props) => {
          const {data} = props ?? {};

          return  createPayment(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePaymentMutationResult = NonNullable<Awaited<ReturnType<typeof createPayment>>>
    export type CreatePaymentMutationBody = BodyType<VnPayRequestDTO>
    export type CreatePaymentMutationError = ErrorType<ErrorVO>

    /**
 * @summary Create VnPay payment
 */
export const useCreatePayment = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPayment>>, TError,{data: BodyType<VnPayRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPayment>>,
        TError,
        {data: BodyType<VnPayRequestDTO>},
        TContext
      > => {

      const mutationOptions = getCreatePaymentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Handle return callback from VnPay after user completes payment
 * @summary Handle VNPAY return
 */
export const handleReturn = (
    
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<string>(
      {url: `/api/v1/payment/return`, method: 'GET', signal
    },
      options);
    }
  



export const getHandleReturnQueryKey = () => {
    return [
    `/api/v1/payment/return`
    ] as const;
    }

    
export const getHandleReturnQueryOptions = <TData = Awaited<ReturnType<typeof handleReturn>>, TError = ErrorType<ErrorVO | RedirectView>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleReturn>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHandleReturnQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof handleReturn>>> = ({ signal }) => handleReturn(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof handleReturn>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandleReturnQueryResult = NonNullable<Awaited<ReturnType<typeof handleReturn>>>
export type HandleReturnQueryError = ErrorType<ErrorVO | RedirectView>


export function useHandleReturn<TData = Awaited<ReturnType<typeof handleReturn>>, TError = ErrorType<ErrorVO | RedirectView>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleReturn>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleReturn>>,
          TError,
          Awaited<ReturnType<typeof handleReturn>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleReturn<TData = Awaited<ReturnType<typeof handleReturn>>, TError = ErrorType<ErrorVO | RedirectView>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleReturn>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleReturn>>,
          TError,
          Awaited<ReturnType<typeof handleReturn>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleReturn<TData = Awaited<ReturnType<typeof handleReturn>>, TError = ErrorType<ErrorVO | RedirectView>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleReturn>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Handle VNPAY return
 */

export function useHandleReturn<TData = Awaited<ReturnType<typeof handleReturn>>, TError = ErrorType<ErrorVO | RedirectView>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleReturn>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHandleReturnQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




