/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Generate a payment URL for VnPay
 * @summary Create VnPay payment
 */
export const createPaymentBody = zod.object({
  "orderId": zod.number().optional(),
  "orderInfo": zod.string().optional(),
  "orderType": zod.string().optional(),
  "bankCode": zod.string().optional(),
  "language": zod.string().optional(),
  "billingMobile": zod.string().optional(),
  "billingEmail": zod.string().optional(),
  "billingFullname": zod.string().optional(),
  "billingAddress": zod.string().optional(),
  "billingCity": zod.string().optional(),
  "billingCountry": zod.string().optional(),
  "billingState": zod.string().optional(),
  "invMobile": zod.string().optional(),
  "invEmail": zod.string().optional(),
  "invCustomer": zod.string().optional(),
  "invAddress": zod.string().optional(),
  "invCompany": zod.string().optional(),
  "invTaxCode": zod.string().optional(),
  "invType": zod.string().optional(),
  "returnUrl": zod.string().optional()
})

