/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Thiết lập xác thực hai yếu tố
 */
export const enableTwoFactorAuthenticationQueryParams = zod.object({
  "method": zod.enum(['TOTP'])
})

/**
 * @summary Xác nhận xác thực hai yếu tố
 */
export const confirmTwoFactorAuthenticationQueryParams = zod.object({
  "code": zod.string(),
  "method": zod.enum(['TOTP'])
})

