/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ConfirmTwoFactorAuthenticationParams,
  EnableTwoFactorAuthenticationParams,
  TwoFASetupResponseDTO,
  VerifySetup2FAResponseDTO
} from '../../types';





/**
 * @summary Thiết lập xác thực hai yếu tố
 */
export const enableTwoFactorAuthentication = (
    params: EnableTwoFactorAuthenticationParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TwoFASetupResponseDTO>> => {
    
    
    return axios.default.post(
      `/2fa/setup-totp`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getEnableTwoFactorAuthenticationMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enableTwoFactorAuthentication>>, TError,{params: EnableTwoFactorAuthenticationParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof enableTwoFactorAuthentication>>, TError,{params: EnableTwoFactorAuthenticationParams}, TContext> => {

const mutationKey = ['enableTwoFactorAuthentication'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof enableTwoFactorAuthentication>>, {params: EnableTwoFactorAuthenticationParams}> = (props) => {
          const {params} = props ?? {};

          return  enableTwoFactorAuthentication(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EnableTwoFactorAuthenticationMutationResult = NonNullable<Awaited<ReturnType<typeof enableTwoFactorAuthentication>>>
    
    export type EnableTwoFactorAuthenticationMutationError = AxiosError<unknown>

    /**
 * @summary Thiết lập xác thực hai yếu tố
 */
export const useEnableTwoFactorAuthentication = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enableTwoFactorAuthentication>>, TError,{params: EnableTwoFactorAuthenticationParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof enableTwoFactorAuthentication>>,
        TError,
        {params: EnableTwoFactorAuthenticationParams},
        TContext
      > => {

      const mutationOptions = getEnableTwoFactorAuthenticationMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Xác nhận xác thực hai yếu tố
 */
export const confirmTwoFactorAuthentication = (
    params: ConfirmTwoFactorAuthenticationParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VerifySetup2FAResponseDTO>> => {
    
    
    return axios.default.post(
      `/2fa/confirm-setup-totp`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getConfirmTwoFactorAuthenticationMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmTwoFactorAuthentication>>, TError,{params: ConfirmTwoFactorAuthenticationParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof confirmTwoFactorAuthentication>>, TError,{params: ConfirmTwoFactorAuthenticationParams}, TContext> => {

const mutationKey = ['confirmTwoFactorAuthentication'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmTwoFactorAuthentication>>, {params: ConfirmTwoFactorAuthenticationParams}> = (props) => {
          const {params} = props ?? {};

          return  confirmTwoFactorAuthentication(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmTwoFactorAuthenticationMutationResult = NonNullable<Awaited<ReturnType<typeof confirmTwoFactorAuthentication>>>
    
    export type ConfirmTwoFactorAuthenticationMutationError = AxiosError<unknown>

    /**
 * @summary Xác nhận xác thực hai yếu tố
 */
export const useConfirmTwoFactorAuthentication = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmTwoFactorAuthentication>>, TError,{params: ConfirmTwoFactorAuthenticationParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof confirmTwoFactorAuthentication>>,
        TError,
        {params: ConfirmTwoFactorAuthenticationParams},
        TContext
      > => {

      const mutationOptions = getConfirmTwoFactorAuthenticationMutationOptions(options);

      return useMutation(mutationOptions);
    }
    