/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Create a new cart for the current user
 * @summary Create a new cart
 */
export const createNewCartBody = zod.object({
  "cartItems": zod.array(zod.object({
  "id": zod.number().optional(),
  "createdAt": zod.string().datetime({}).optional(),
  "updatedAt": zod.string().datetime({}).optional(),
  "createdBy": zod.number().optional(),
  "updatedBy": zod.number().optional(),
  "product": zod.object({
  "id": zod.number().optional(),
  "createdAt": zod.string().datetime({}).optional(),
  "updatedAt": zod.string().datetime({}).optional(),
  "createdBy": zod.number().optional(),
  "updatedBy": zod.number().optional(),
  "category": zod.object({
  "id": zod.number().optional(),
  "createdAt": zod.string().datetime({}).optional(),
  "updatedAt": zod.string().datetime({}).optional(),
  "createdBy": zod.number().optional(),
  "updatedBy": zod.number().optional(),
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "products": zod.array(zod.unknown()).optional(),
  "imageUrl": zod.string().optional()
}).optional(),
  "variations": zod.array(zod.object({
  "id": zod.number().optional(),
  "createdAt": zod.string().datetime({}).optional(),
  "updatedAt": zod.string().datetime({}).optional(),
  "createdBy": zod.number().optional(),
  "updatedBy": zod.number().optional(),
  "product": zod.unknown().optional(),
  "name": zod.string(),
  "variationOptions": zod.array(zod.object({
  "id": zod.number().optional(),
  "createdAt": zod.string().datetime({}).optional(),
  "updatedAt": zod.string().datetime({}).optional(),
  "createdBy": zod.number().optional(),
  "updatedBy": zod.number().optional(),
  "value": zod.string(),
  "additionalPrice": zod.number(),
  "variation": zod.unknown().optional(),
  "cartItems": zod.array(zod.unknown()).optional()
})).optional(),
  "isMultipleChoice": zod.boolean().optional()
})).optional(),
  "name": zod.string(),
  "shortDescription": zod.string().optional(),
  "detailDescription": zod.string().optional(),
  "originalPrice": zod.number(),
  "imageUrl": zod.string().optional(),
  "isAvailable": zod.boolean(),
  "deleted": zod.boolean().optional(),
  "cartItems": zod.array(zod.unknown()).optional()
}).optional(),
  "quantity": zod.number(),
  "price": zod.number(),
  "variationOptions": zod.array(zod.object({
  "id": zod.number().optional(),
  "createdAt": zod.string().datetime({}).optional(),
  "updatedAt": zod.string().datetime({}).optional(),
  "createdBy": zod.number().optional(),
  "updatedBy": zod.number().optional(),
  "value": zod.string(),
  "additionalPrice": zod.number(),
  "variation": zod.object({
  "id": zod.number().optional(),
  "createdAt": zod.string().datetime({}).optional(),
  "updatedAt": zod.string().datetime({}).optional(),
  "createdBy": zod.number().optional(),
  "updatedBy": zod.number().optional(),
  "product": zod.object({
  "id": zod.number().optional(),
  "createdAt": zod.string().datetime({}).optional(),
  "updatedAt": zod.string().datetime({}).optional(),
  "createdBy": zod.number().optional(),
  "updatedBy": zod.number().optional(),
  "category": zod.object({
  "id": zod.number().optional(),
  "createdAt": zod.string().datetime({}).optional(),
  "updatedAt": zod.string().datetime({}).optional(),
  "createdBy": zod.number().optional(),
  "updatedBy": zod.number().optional(),
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "products": zod.array(zod.unknown()).optional(),
  "imageUrl": zod.string().optional()
}).optional(),
  "variations": zod.array(zod.unknown()).optional(),
  "name": zod.string(),
  "shortDescription": zod.string().optional(),
  "detailDescription": zod.string().optional(),
  "originalPrice": zod.number(),
  "imageUrl": zod.string().optional(),
  "isAvailable": zod.boolean(),
  "deleted": zod.boolean().optional(),
  "cartItems": zod.array(zod.unknown()).optional()
}).optional(),
  "name": zod.string(),
  "variationOptions": zod.array(zod.unknown()).optional(),
  "isMultipleChoice": zod.boolean().optional()
}).optional(),
  "cartItems": zod.array(zod.unknown()).optional()
})).optional(),
  "available": zod.boolean().optional()
})).optional()
})

/**
 * Retrieve a cart by its ID
 * @summary Get cart by ID
 */
export const getCartByIdParams = zod.object({
  "id": zod.number()
})

/**
 * Delete a cart belonging to the current user
 * @summary Delete a cart by ID
 */
export const deleteCartParams = zod.object({
  "id": zod.number().describe('ID of the cart to be deleted')
})

