/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Update reviews
 */
export const updateReviewParams = zod.object({
  "reviewId": zod.number()
})

export const updateReviewBodyRateMax = 5;



export const updateReviewBody = zod.object({
  "orderId": zod.number(),
  "rate": zod.number().min(1).max(updateReviewBodyRateMax),
  "content": zod.string().optional(),
  "reply": zod.string().optional()
})

/**
 * Delete a review by the id
 * @summary Delete review
 */
export const deleteReviewParams = zod.object({
  "reviewId": zod.number()
})

/**
 * Return the list of reviews
 * @summary Get all reviews
 */
export const getAllReviewsQueryPageDefault = 0;
export const getAllReviewsQueryPageMin = 0;

export const getAllReviewsQuerySizeDefault = 20;



export const getAllReviewsQueryParams = zod.object({
  "page": zod.number().min(getAllReviewsQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getAllReviewsQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.')
})

/**
 * Create a new review for the completed order
 * @summary Create a new review
 */
export const createReviewBodyRateMax = 5;



export const createReviewBody = zod.object({
  "orderId": zod.number(),
  "rate": zod.number().min(1).max(createReviewBodyRateMax),
  "content": zod.string().optional(),
  "reply": zod.string().optional()
})

/**
 * Add new content to the reply
 * @summary Create a reply to the review
 */
export const replyToReviewParams = zod.object({
  "reviewId": zod.number()
})

export const replyToReviewQueryParams = zod.object({
  "arg1": zod.string()
})

/**
 * Return the list of reviews related to the order
 * @summary Get the review of the order
 */
export const getReviewsByOrderParams = zod.object({
  "orderId": zod.number()
})

