/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorVO,
  GetAllReviewsParams,
  PageVOReviewResponseDTO,
  ReplyToReviewParams,
  ReviewRequestDTO,
  ReviewResponseDTO
} from '../../types';





/**
 * @summary Update reviews
 */
export const updateReview = (
    reviewId: number,
    reviewRequestDTO: ReviewRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReviewResponseDTO>> => {
    
    
    return axios.default.put(
      `/api/v1/reviews/${reviewId}`,
      reviewRequestDTO,options
    );
  }



export const getUpdateReviewMutationOptions = <TError = AxiosError<ErrorVO | ReviewResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReview>>, TError,{reviewId: number;data: ReviewRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateReview>>, TError,{reviewId: number;data: ReviewRequestDTO}, TContext> => {

const mutationKey = ['updateReview'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateReview>>, {reviewId: number;data: ReviewRequestDTO}> = (props) => {
          const {reviewId,data} = props ?? {};

          return  updateReview(reviewId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateReviewMutationResult = NonNullable<Awaited<ReturnType<typeof updateReview>>>
    export type UpdateReviewMutationBody = ReviewRequestDTO
    export type UpdateReviewMutationError = AxiosError<ErrorVO | ReviewResponseDTO>

    /**
 * @summary Update reviews
 */
export const useUpdateReview = <TError = AxiosError<ErrorVO | ReviewResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReview>>, TError,{reviewId: number;data: ReviewRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateReview>>,
        TError,
        {reviewId: number;data: ReviewRequestDTO},
        TContext
      > => {

      const mutationOptions = getUpdateReviewMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Delete a review by the id
 * @summary Delete review
 */
export const deleteReview = (
    reviewId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/v1/reviews/${reviewId}`,options
    );
  }



export const getDeleteReviewMutationOptions = <TError = AxiosError<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReview>>, TError,{reviewId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReview>>, TError,{reviewId: number}, TContext> => {

const mutationKey = ['deleteReview'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReview>>, {reviewId: number}> = (props) => {
          const {reviewId} = props ?? {};

          return  deleteReview(reviewId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteReviewMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReview>>>
    
    export type DeleteReviewMutationError = AxiosError<ErrorVO | void>

    /**
 * @summary Delete review
 */
export const useDeleteReview = <TError = AxiosError<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReview>>, TError,{reviewId: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteReview>>,
        TError,
        {reviewId: number},
        TContext
      > => {

      const mutationOptions = getDeleteReviewMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Return the list of reviews
 * @summary Get all reviews
 */
export const getAllReviews = (
    params?: GetAllReviewsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PageVOReviewResponseDTO>> => {
    
    
    return axios.default.get(
      `/api/v1/reviews`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAllReviewsQueryKey = (params?: GetAllReviewsParams,) => {
    return [
    `/api/v1/reviews`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllReviewsQueryOptions = <TData = Awaited<ReturnType<typeof getAllReviews>>, TError = AxiosError<ErrorVO | PageVOReviewResponseDTO>>(params?: GetAllReviewsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllReviews>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllReviewsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllReviews>>> = ({ signal }) => getAllReviews(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllReviews>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllReviewsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllReviews>>>
export type GetAllReviewsQueryError = AxiosError<ErrorVO | PageVOReviewResponseDTO>


/**
 * @summary Get all reviews
 */

export function useGetAllReviews<TData = Awaited<ReturnType<typeof getAllReviews>>, TError = AxiosError<ErrorVO | PageVOReviewResponseDTO>>(
 params?: GetAllReviewsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllReviews>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllReviewsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new review for the completed order
 * @summary Create a new review
 */
export const createReview = (
    reviewRequestDTO: ReviewRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReviewResponseDTO>> => {
    
    
    return axios.default.post(
      `/api/v1/reviews`,
      reviewRequestDTO,options
    );
  }



export const getCreateReviewMutationOptions = <TError = AxiosError<ErrorVO | ReviewResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReview>>, TError,{data: ReviewRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createReview>>, TError,{data: ReviewRequestDTO}, TContext> => {

const mutationKey = ['createReview'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReview>>, {data: ReviewRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  createReview(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateReviewMutationResult = NonNullable<Awaited<ReturnType<typeof createReview>>>
    export type CreateReviewMutationBody = ReviewRequestDTO
    export type CreateReviewMutationError = AxiosError<ErrorVO | ReviewResponseDTO>

    /**
 * @summary Create a new review
 */
export const useCreateReview = <TError = AxiosError<ErrorVO | ReviewResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReview>>, TError,{data: ReviewRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createReview>>,
        TError,
        {data: ReviewRequestDTO},
        TContext
      > => {

      const mutationOptions = getCreateReviewMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Add new content to the reply
 * @summary Create a reply to the review
 */
export const replyToReview = (
    reviewId: number,
    params: ReplyToReviewParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReviewResponseDTO>> => {
    
    
    return axios.default.patch(
      `/api/v1/reviews/${reviewId}/reply`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getReplyToReviewMutationOptions = <TError = AxiosError<ErrorVO | ReviewResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replyToReview>>, TError,{reviewId: number;params: ReplyToReviewParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof replyToReview>>, TError,{reviewId: number;params: ReplyToReviewParams}, TContext> => {

const mutationKey = ['replyToReview'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replyToReview>>, {reviewId: number;params: ReplyToReviewParams}> = (props) => {
          const {reviewId,params} = props ?? {};

          return  replyToReview(reviewId,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReplyToReviewMutationResult = NonNullable<Awaited<ReturnType<typeof replyToReview>>>
    
    export type ReplyToReviewMutationError = AxiosError<ErrorVO | ReviewResponseDTO>

    /**
 * @summary Create a reply to the review
 */
export const useReplyToReview = <TError = AxiosError<ErrorVO | ReviewResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replyToReview>>, TError,{reviewId: number;params: ReplyToReviewParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof replyToReview>>,
        TError,
        {reviewId: number;params: ReplyToReviewParams},
        TContext
      > => {

      const mutationOptions = getReplyToReviewMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Return the list of reviews related to the order
 * @summary Get the review of the order
 */
export const getReviewsByOrder = (
    orderId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReviewResponseDTO>> => {
    
    
    return axios.default.get(
      `/api/v1/reviews/order/${orderId}`,options
    );
  }




export const getGetReviewsByOrderQueryKey = (orderId?: number,) => {
    return [
    `/api/v1/reviews/order/${orderId}`
    ] as const;
    }

    
export const getGetReviewsByOrderQueryOptions = <TData = Awaited<ReturnType<typeof getReviewsByOrder>>, TError = AxiosError<ErrorVO | ReviewResponseDTO>>(orderId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOrder>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReviewsByOrderQueryKey(orderId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReviewsByOrder>>> = ({ signal }) => getReviewsByOrder(orderId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(orderId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOrder>>, TError, TData> & { queryKey: QueryKey }
}

export type GetReviewsByOrderQueryResult = NonNullable<Awaited<ReturnType<typeof getReviewsByOrder>>>
export type GetReviewsByOrderQueryError = AxiosError<ErrorVO | ReviewResponseDTO>


/**
 * @summary Get the review of the order
 */

export function useGetReviewsByOrder<TData = Awaited<ReturnType<typeof getReviewsByOrder>>, TError = AxiosError<ErrorVO | ReviewResponseDTO>>(
 orderId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOrder>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetReviewsByOrderQueryOptions(orderId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




