/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorVO,
  GetAllReviewsParams,
  PageVOReviewResponseDTO,
  ReplyToReviewParams,
  ReviewRequestDTO,
  ReviewResponseDTO
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Update reviews
 */
export const updateReview = (
    reviewId: number,
    reviewRequestDTO: BodyType<ReviewRequestDTO>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ReviewResponseDTO>(
      {url: `/api/v1/reviews/${reviewId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: reviewRequestDTO
    },
      options);
    }
  


export const getUpdateReviewMutationOptions = <TError = ErrorType<ErrorVO | ReviewResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReview>>, TError,{reviewId: number;data: BodyType<ReviewRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateReview>>, TError,{reviewId: number;data: BodyType<ReviewRequestDTO>}, TContext> => {

const mutationKey = ['updateReview'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateReview>>, {reviewId: number;data: BodyType<ReviewRequestDTO>}> = (props) => {
          const {reviewId,data} = props ?? {};

          return  updateReview(reviewId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateReviewMutationResult = NonNullable<Awaited<ReturnType<typeof updateReview>>>
    export type UpdateReviewMutationBody = BodyType<ReviewRequestDTO>
    export type UpdateReviewMutationError = ErrorType<ErrorVO | ReviewResponseDTO>

    /**
 * @summary Update reviews
 */
export const useUpdateReview = <TError = ErrorType<ErrorVO | ReviewResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReview>>, TError,{reviewId: number;data: BodyType<ReviewRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateReview>>,
        TError,
        {reviewId: number;data: BodyType<ReviewRequestDTO>},
        TContext
      > => {

      const mutationOptions = getUpdateReviewMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a review by the id
 * @summary Delete review
 */
export const deleteReview = (
    reviewId: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<void>(
      {url: `/api/v1/reviews/${reviewId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteReviewMutationOptions = <TError = ErrorType<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReview>>, TError,{reviewId: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReview>>, TError,{reviewId: number}, TContext> => {

const mutationKey = ['deleteReview'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReview>>, {reviewId: number}> = (props) => {
          const {reviewId} = props ?? {};

          return  deleteReview(reviewId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteReviewMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReview>>>
    
    export type DeleteReviewMutationError = ErrorType<ErrorVO | void>

    /**
 * @summary Delete review
 */
export const useDeleteReview = <TError = ErrorType<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReview>>, TError,{reviewId: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteReview>>,
        TError,
        {reviewId: number},
        TContext
      > => {

      const mutationOptions = getDeleteReviewMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Return the list of reviews
 * @summary Get all reviews
 */
export const getAllReviews = (
    params?: GetAllReviewsParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<PageVOReviewResponseDTO>(
      {url: `/api/v1/reviews`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllReviewsQueryKey = (params?: GetAllReviewsParams,) => {
    return [
    `/api/v1/reviews`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllReviewsQueryOptions = <TData = Awaited<ReturnType<typeof getAllReviews>>, TError = ErrorType<ErrorVO | PageVOReviewResponseDTO>>(params?: GetAllReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllReviews>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllReviewsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllReviews>>> = ({ signal }) => getAllReviews(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllReviews>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllReviewsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllReviews>>>
export type GetAllReviewsQueryError = ErrorType<ErrorVO | PageVOReviewResponseDTO>


export function useGetAllReviews<TData = Awaited<ReturnType<typeof getAllReviews>>, TError = ErrorType<ErrorVO | PageVOReviewResponseDTO>>(
 params: undefined |  GetAllReviewsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllReviews>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllReviews>>,
          TError,
          Awaited<ReturnType<typeof getAllReviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllReviews<TData = Awaited<ReturnType<typeof getAllReviews>>, TError = ErrorType<ErrorVO | PageVOReviewResponseDTO>>(
 params?: GetAllReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllReviews>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllReviews>>,
          TError,
          Awaited<ReturnType<typeof getAllReviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllReviews<TData = Awaited<ReturnType<typeof getAllReviews>>, TError = ErrorType<ErrorVO | PageVOReviewResponseDTO>>(
 params?: GetAllReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllReviews>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all reviews
 */

export function useGetAllReviews<TData = Awaited<ReturnType<typeof getAllReviews>>, TError = ErrorType<ErrorVO | PageVOReviewResponseDTO>>(
 params?: GetAllReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllReviews>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllReviewsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new review for the completed order
 * @summary Create a new review
 */
export const createReview = (
    reviewRequestDTO: BodyType<ReviewRequestDTO>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ReviewResponseDTO>(
      {url: `/api/v1/reviews`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reviewRequestDTO, signal
    },
      options);
    }
  


export const getCreateReviewMutationOptions = <TError = ErrorType<ErrorVO | ReviewResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReview>>, TError,{data: BodyType<ReviewRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createReview>>, TError,{data: BodyType<ReviewRequestDTO>}, TContext> => {

const mutationKey = ['createReview'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReview>>, {data: BodyType<ReviewRequestDTO>}> = (props) => {
          const {data} = props ?? {};

          return  createReview(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateReviewMutationResult = NonNullable<Awaited<ReturnType<typeof createReview>>>
    export type CreateReviewMutationBody = BodyType<ReviewRequestDTO>
    export type CreateReviewMutationError = ErrorType<ErrorVO | ReviewResponseDTO>

    /**
 * @summary Create a new review
 */
export const useCreateReview = <TError = ErrorType<ErrorVO | ReviewResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReview>>, TError,{data: BodyType<ReviewRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createReview>>,
        TError,
        {data: BodyType<ReviewRequestDTO>},
        TContext
      > => {

      const mutationOptions = getCreateReviewMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Add new content to the reply
 * @summary Create a reply to the review
 */
export const replyToReview = (
    reviewId: number,
    params: ReplyToReviewParams,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ReviewResponseDTO>(
      {url: `/api/v1/reviews/${reviewId}/reply`, method: 'PATCH',
        params
    },
      options);
    }
  


export const getReplyToReviewMutationOptions = <TError = ErrorType<ErrorVO | ReviewResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replyToReview>>, TError,{reviewId: number;params: ReplyToReviewParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof replyToReview>>, TError,{reviewId: number;params: ReplyToReviewParams}, TContext> => {

const mutationKey = ['replyToReview'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replyToReview>>, {reviewId: number;params: ReplyToReviewParams}> = (props) => {
          const {reviewId,params} = props ?? {};

          return  replyToReview(reviewId,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReplyToReviewMutationResult = NonNullable<Awaited<ReturnType<typeof replyToReview>>>
    
    export type ReplyToReviewMutationError = ErrorType<ErrorVO | ReviewResponseDTO>

    /**
 * @summary Create a reply to the review
 */
export const useReplyToReview = <TError = ErrorType<ErrorVO | ReviewResponseDTO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replyToReview>>, TError,{reviewId: number;params: ReplyToReviewParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof replyToReview>>,
        TError,
        {reviewId: number;params: ReplyToReviewParams},
        TContext
      > => {

      const mutationOptions = getReplyToReviewMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Return the list of reviews related to the order
 * @summary Get the review of the order
 */
export const getReviewsByOrder = (
    orderId: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ReviewResponseDTO>(
      {url: `/api/v1/reviews/order/${orderId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetReviewsByOrderQueryKey = (orderId?: number,) => {
    return [
    `/api/v1/reviews/order/${orderId}`
    ] as const;
    }

    
export const getGetReviewsByOrderQueryOptions = <TData = Awaited<ReturnType<typeof getReviewsByOrder>>, TError = ErrorType<ErrorVO | ReviewResponseDTO>>(orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOrder>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReviewsByOrderQueryKey(orderId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReviewsByOrder>>> = ({ signal }) => getReviewsByOrder(orderId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(orderId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOrder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReviewsByOrderQueryResult = NonNullable<Awaited<ReturnType<typeof getReviewsByOrder>>>
export type GetReviewsByOrderQueryError = ErrorType<ErrorVO | ReviewResponseDTO>


export function useGetReviewsByOrder<TData = Awaited<ReturnType<typeof getReviewsByOrder>>, TError = ErrorType<ErrorVO | ReviewResponseDTO>>(
 orderId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOrder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReviewsByOrder>>,
          TError,
          Awaited<ReturnType<typeof getReviewsByOrder>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReviewsByOrder<TData = Awaited<ReturnType<typeof getReviewsByOrder>>, TError = ErrorType<ErrorVO | ReviewResponseDTO>>(
 orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOrder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReviewsByOrder>>,
          TError,
          Awaited<ReturnType<typeof getReviewsByOrder>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReviewsByOrder<TData = Awaited<ReturnType<typeof getReviewsByOrder>>, TError = ErrorType<ErrorVO | ReviewResponseDTO>>(
 orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOrder>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the review of the order
 */

export function useGetReviewsByOrder<TData = Awaited<ReturnType<typeof getReviewsByOrder>>, TError = ErrorType<ErrorVO | ReviewResponseDTO>>(
 orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOrder>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReviewsByOrderQueryOptions(orderId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




