/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Update variation details by its ID
 * @summary Update an existing variation
 */
export const updateVariationParams = zod.object({
  "id": zod.number().describe('ID of the variation to update')
})

export const updateVariationBody = zod.object({
  "name": zod.string(),
  "isMultipleChoice": zod.boolean(),
  "productId": zod.number()
})

/**
 * Delete a variation by its ID
 * @summary Delete a variation
 */
export const deleteVariationParams = zod.object({
  "id": zod.number().describe('ID of the variation to delete')
})

/**
 * Retrieve a paginated list of variations for a specific product, optionally filtered by name
 * @summary Get variations by product ID
 */
export const getVariationsByProductQueryPageDefault = 0;
export const getVariationsByProductQueryPageMin = 0;

export const getVariationsByProductQuerySizeDefault = 20;



export const getVariationsByProductQueryParams = zod.object({
  "arg0": zod.number().describe('ID of the product'),
  "arg1": zod.string().optional().describe('Filter by variation name (optional)'),
  "page": zod.number().min(getVariationsByProductQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getVariationsByProductQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.')
})

/**
 * Create a new variation for a product
 * @summary Create a new variation
 */
export const createVariationBody = zod.object({
  "name": zod.string(),
  "isMultipleChoice": zod.boolean(),
  "productId": zod.number()
})

