/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorVO,
  GetVariationsByProductParams,
  PageVO,
  VariationRequestDTO,
  VariationResponseDTO
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Update variation details by its ID
 * @summary Update an existing variation
 */
export const updateVariation = (
    id: number,
    variationRequestDTO: BodyType<VariationRequestDTO>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<VariationResponseDTO>(
      {url: `/api/v1/variations/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: variationRequestDTO
    },
      options);
    }
  


export const getUpdateVariationMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVariation>>, TError,{id: number;data: BodyType<VariationRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateVariation>>, TError,{id: number;data: BodyType<VariationRequestDTO>}, TContext> => {

const mutationKey = ['updateVariation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateVariation>>, {id: number;data: BodyType<VariationRequestDTO>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateVariation(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateVariationMutationResult = NonNullable<Awaited<ReturnType<typeof updateVariation>>>
    export type UpdateVariationMutationBody = BodyType<VariationRequestDTO>
    export type UpdateVariationMutationError = ErrorType<ErrorVO>

    /**
 * @summary Update an existing variation
 */
export const useUpdateVariation = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVariation>>, TError,{id: number;data: BodyType<VariationRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateVariation>>,
        TError,
        {id: number;data: BodyType<VariationRequestDTO>},
        TContext
      > => {

      const mutationOptions = getUpdateVariationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a variation by its ID
 * @summary Delete a variation
 */
export const deleteVariation = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<void>(
      {url: `/api/v1/variations/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteVariationMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVariation>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteVariation>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteVariation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteVariation>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteVariation(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteVariationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVariation>>>
    
    export type DeleteVariationMutationError = ErrorType<ErrorVO>

    /**
 * @summary Delete a variation
 */
export const useDeleteVariation = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVariation>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteVariation>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteVariationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a paginated list of variations for a specific product, optionally filtered by name
 * @summary Get variations by product ID
 */
export const getVariationsByProduct = (
    params: GetVariationsByProductParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<PageVO>(
      {url: `/api/v1/variations`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetVariationsByProductQueryKey = (params?: GetVariationsByProductParams,) => {
    return [
    `/api/v1/variations`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetVariationsByProductQueryOptions = <TData = Awaited<ReturnType<typeof getVariationsByProduct>>, TError = ErrorType<ErrorVO>>(params: GetVariationsByProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVariationsByProduct>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVariationsByProductQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVariationsByProduct>>> = ({ signal }) => getVariationsByProduct(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVariationsByProduct>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVariationsByProductQueryResult = NonNullable<Awaited<ReturnType<typeof getVariationsByProduct>>>
export type GetVariationsByProductQueryError = ErrorType<ErrorVO>


export function useGetVariationsByProduct<TData = Awaited<ReturnType<typeof getVariationsByProduct>>, TError = ErrorType<ErrorVO>>(
 params: GetVariationsByProductParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVariationsByProduct>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVariationsByProduct>>,
          TError,
          Awaited<ReturnType<typeof getVariationsByProduct>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVariationsByProduct<TData = Awaited<ReturnType<typeof getVariationsByProduct>>, TError = ErrorType<ErrorVO>>(
 params: GetVariationsByProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVariationsByProduct>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVariationsByProduct>>,
          TError,
          Awaited<ReturnType<typeof getVariationsByProduct>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVariationsByProduct<TData = Awaited<ReturnType<typeof getVariationsByProduct>>, TError = ErrorType<ErrorVO>>(
 params: GetVariationsByProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVariationsByProduct>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get variations by product ID
 */

export function useGetVariationsByProduct<TData = Awaited<ReturnType<typeof getVariationsByProduct>>, TError = ErrorType<ErrorVO>>(
 params: GetVariationsByProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVariationsByProduct>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVariationsByProductQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new variation for a product
 * @summary Create a new variation
 */
export const createVariation = (
    variationRequestDTO: BodyType<VariationRequestDTO>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<VariationResponseDTO>(
      {url: `/api/v1/variations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: variationRequestDTO, signal
    },
      options);
    }
  


export const getCreateVariationMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVariation>>, TError,{data: BodyType<VariationRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createVariation>>, TError,{data: BodyType<VariationRequestDTO>}, TContext> => {

const mutationKey = ['createVariation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createVariation>>, {data: BodyType<VariationRequestDTO>}> = (props) => {
          const {data} = props ?? {};

          return  createVariation(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateVariationMutationResult = NonNullable<Awaited<ReturnType<typeof createVariation>>>
    export type CreateVariationMutationBody = BodyType<VariationRequestDTO>
    export type CreateVariationMutationError = ErrorType<ErrorVO>

    /**
 * @summary Create a new variation
 */
export const useCreateVariation = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVariation>>, TError,{data: BodyType<VariationRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createVariation>>,
        TError,
        {data: BodyType<VariationRequestDTO>},
        TContext
      > => {

      const mutationOptions = getCreateVariationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    