/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorVO,
  GetVariationsByProductParams,
  PageVO,
  VariationRequestDTO,
  VariationResponseDTO
} from '../../types';





/**
 * Update variation details by its ID
 * @summary Update an existing variation
 */
export const updateVariation = (
    id: number,
    variationRequestDTO: VariationRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VariationResponseDTO>> => {
    
    
    return axios.default.put(
      `/api/v1/variations/${id}`,
      variationRequestDTO,options
    );
  }



export const getUpdateVariationMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVariation>>, TError,{id: number;data: VariationRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateVariation>>, TError,{id: number;data: VariationRequestDTO}, TContext> => {

const mutationKey = ['updateVariation'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateVariation>>, {id: number;data: VariationRequestDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  updateVariation(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateVariationMutationResult = NonNullable<Awaited<ReturnType<typeof updateVariation>>>
    export type UpdateVariationMutationBody = VariationRequestDTO
    export type UpdateVariationMutationError = AxiosError<ErrorVO>

    /**
 * @summary Update an existing variation
 */
export const useUpdateVariation = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVariation>>, TError,{id: number;data: VariationRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateVariation>>,
        TError,
        {id: number;data: VariationRequestDTO},
        TContext
      > => {

      const mutationOptions = getUpdateVariationMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Delete a variation by its ID
 * @summary Delete a variation
 */
export const deleteVariation = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/v1/variations/${id}`,options
    );
  }



export const getDeleteVariationMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVariation>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteVariation>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteVariation'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteVariation>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteVariation(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteVariationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVariation>>>
    
    export type DeleteVariationMutationError = AxiosError<ErrorVO>

    /**
 * @summary Delete a variation
 */
export const useDeleteVariation = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVariation>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteVariation>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteVariationMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Retrieve a paginated list of variations for a specific product, optionally filtered by name
 * @summary Get variations by product ID
 */
export const getVariationsByProduct = (
    params: GetVariationsByProductParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PageVO>> => {
    
    
    return axios.default.get(
      `/api/v1/variations`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetVariationsByProductQueryKey = (params?: GetVariationsByProductParams,) => {
    return [
    `/api/v1/variations`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetVariationsByProductQueryOptions = <TData = Awaited<ReturnType<typeof getVariationsByProduct>>, TError = AxiosError<ErrorVO>>(params: GetVariationsByProductParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getVariationsByProduct>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVariationsByProductQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVariationsByProduct>>> = ({ signal }) => getVariationsByProduct(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVariationsByProduct>>, TError, TData> & { queryKey: QueryKey }
}

export type GetVariationsByProductQueryResult = NonNullable<Awaited<ReturnType<typeof getVariationsByProduct>>>
export type GetVariationsByProductQueryError = AxiosError<ErrorVO>


/**
 * @summary Get variations by product ID
 */

export function useGetVariationsByProduct<TData = Awaited<ReturnType<typeof getVariationsByProduct>>, TError = AxiosError<ErrorVO>>(
 params: GetVariationsByProductParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getVariationsByProduct>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetVariationsByProductQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new variation for a product
 * @summary Create a new variation
 */
export const createVariation = (
    variationRequestDTO: VariationRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VariationResponseDTO>> => {
    
    
    return axios.default.post(
      `/api/v1/variations`,
      variationRequestDTO,options
    );
  }



export const getCreateVariationMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVariation>>, TError,{data: VariationRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createVariation>>, TError,{data: VariationRequestDTO}, TContext> => {

const mutationKey = ['createVariation'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createVariation>>, {data: VariationRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  createVariation(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateVariationMutationResult = NonNullable<Awaited<ReturnType<typeof createVariation>>>
    export type CreateVariationMutationBody = VariationRequestDTO
    export type CreateVariationMutationError = AxiosError<ErrorVO>

    /**
 * @summary Create a new variation
 */
export const useCreateVariation = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVariation>>, TError,{data: VariationRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createVariation>>,
        TError,
        {data: VariationRequestDTO},
        TContext
      > => {

      const mutationOptions = getCreateVariationMutationOptions(options);

      return useMutation(mutationOptions);
    }
    