/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Marks a promotion as used by the user (e.g., after a successful order)
 * @summary Mark promotion as used
 */
export const markPromotionAsUsedQueryParams = zod.object({
  "arg0": zod.number().describe('User ID'),
  "arg1": zod.number().describe('Promotion ID')
})

/**
 * Returns all unused and valid promotions for the given user
 * @summary Get available promotions for a user
 */
export const getAvailablePromotionsQueryParams = zod.object({
  "arg0": zod.number().describe('User ID')
})

/**
 * Returns promotions that a user can use for a given order value
 * @summary Get promotions applicable for an order
 */
export const getAvailablePromotionsForOrderQueryParams = zod.object({
  "arg0": zod.number().describe('User ID'),
  "arg1": zod.number().describe('Order total value')
})

