/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorVO,
  GetAvailablePromotionsForOrderParams,
  GetAvailablePromotionsParams,
  MarkPromotionAsUsedParams,
  PromotionResponseDTO
} from '../../types';





/**
 * Marks a promotion as used by the user (e.g., after a successful order)
 * @summary Mark promotion as used
 */
export const markPromotionAsUsed = (
    params: MarkPromotionAsUsedParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/v1/user-promotions/use`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getMarkPromotionAsUsedMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markPromotionAsUsed>>, TError,{params: MarkPromotionAsUsedParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof markPromotionAsUsed>>, TError,{params: MarkPromotionAsUsedParams}, TContext> => {

const mutationKey = ['markPromotionAsUsed'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markPromotionAsUsed>>, {params: MarkPromotionAsUsedParams}> = (props) => {
          const {params} = props ?? {};

          return  markPromotionAsUsed(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarkPromotionAsUsedMutationResult = NonNullable<Awaited<ReturnType<typeof markPromotionAsUsed>>>
    
    export type MarkPromotionAsUsedMutationError = AxiosError<ErrorVO>

    /**
 * @summary Mark promotion as used
 */
export const useMarkPromotionAsUsed = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markPromotionAsUsed>>, TError,{params: MarkPromotionAsUsedParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof markPromotionAsUsed>>,
        TError,
        {params: MarkPromotionAsUsedParams},
        TContext
      > => {

      const mutationOptions = getMarkPromotionAsUsedMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Returns all unused and valid promotions for the given user
 * @summary Get available promotions for a user
 */
export const getAvailablePromotions = (
    params: GetAvailablePromotionsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PromotionResponseDTO[]>> => {
    
    
    return axios.default.get(
      `/api/v1/user-promotions/available`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAvailablePromotionsQueryKey = (params?: GetAvailablePromotionsParams,) => {
    return [
    `/api/v1/user-promotions/available`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAvailablePromotionsQueryOptions = <TData = Awaited<ReturnType<typeof getAvailablePromotions>>, TError = AxiosError<ErrorVO>>(params: GetAvailablePromotionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotions>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAvailablePromotionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAvailablePromotions>>> = ({ signal }) => getAvailablePromotions(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAvailablePromotionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAvailablePromotions>>>
export type GetAvailablePromotionsQueryError = AxiosError<ErrorVO>


/**
 * @summary Get available promotions for a user
 */

export function useGetAvailablePromotions<TData = Awaited<ReturnType<typeof getAvailablePromotions>>, TError = AxiosError<ErrorVO>>(
 params: GetAvailablePromotionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotions>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAvailablePromotionsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns promotions that a user can use for a given order value
 * @summary Get promotions applicable for an order
 */
export const getAvailablePromotionsForOrder = (
    params: GetAvailablePromotionsForOrderParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PromotionResponseDTO[]>> => {
    
    
    return axios.default.get(
      `/api/v1/user-promotions/available-for-order`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAvailablePromotionsForOrderQueryKey = (params?: GetAvailablePromotionsForOrderParams,) => {
    return [
    `/api/v1/user-promotions/available-for-order`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAvailablePromotionsForOrderQueryOptions = <TData = Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError = AxiosError<ErrorVO>>(params: GetAvailablePromotionsForOrderParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAvailablePromotionsForOrderQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>> = ({ signal }) => getAvailablePromotionsForOrder(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAvailablePromotionsForOrderQueryResult = NonNullable<Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>>
export type GetAvailablePromotionsForOrderQueryError = AxiosError<ErrorVO>


/**
 * @summary Get promotions applicable for an order
 */

export function useGetAvailablePromotionsForOrder<TData = Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError = AxiosError<ErrorVO>>(
 params: GetAvailablePromotionsForOrderParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAvailablePromotionsForOrderQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




