/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorVO,
  GetAvailablePromotionsForOrderParams,
  GetAvailablePromotionsParams,
  MarkPromotionAsUsedParams,
  PromotionResponseDTO
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Marks a promotion as used by the user (e.g., after a successful order)
 * @summary Mark promotion as used
 */
export const markPromotionAsUsed = (
    params: MarkPromotionAsUsedParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<void>(
      {url: `/api/v1/user-promotions/use`, method: 'POST',
        params, signal
    },
      options);
    }
  


export const getMarkPromotionAsUsedMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markPromotionAsUsed>>, TError,{params: MarkPromotionAsUsedParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof markPromotionAsUsed>>, TError,{params: MarkPromotionAsUsedParams}, TContext> => {

const mutationKey = ['markPromotionAsUsed'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markPromotionAsUsed>>, {params: MarkPromotionAsUsedParams}> = (props) => {
          const {params} = props ?? {};

          return  markPromotionAsUsed(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarkPromotionAsUsedMutationResult = NonNullable<Awaited<ReturnType<typeof markPromotionAsUsed>>>
    
    export type MarkPromotionAsUsedMutationError = ErrorType<ErrorVO>

    /**
 * @summary Mark promotion as used
 */
export const useMarkPromotionAsUsed = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markPromotionAsUsed>>, TError,{params: MarkPromotionAsUsedParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markPromotionAsUsed>>,
        TError,
        {params: MarkPromotionAsUsedParams},
        TContext
      > => {

      const mutationOptions = getMarkPromotionAsUsedMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns all unused and valid promotions for the given user
 * @summary Get available promotions for a user
 */
export const getAvailablePromotions = (
    params: GetAvailablePromotionsParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<PromotionResponseDTO[]>(
      {url: `/api/v1/user-promotions/available`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAvailablePromotionsQueryKey = (params?: GetAvailablePromotionsParams,) => {
    return [
    `/api/v1/user-promotions/available`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAvailablePromotionsQueryOptions = <TData = Awaited<ReturnType<typeof getAvailablePromotions>>, TError = ErrorType<ErrorVO>>(params: GetAvailablePromotionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotions>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAvailablePromotionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAvailablePromotions>>> = ({ signal }) => getAvailablePromotions(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAvailablePromotionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAvailablePromotions>>>
export type GetAvailablePromotionsQueryError = ErrorType<ErrorVO>


export function useGetAvailablePromotions<TData = Awaited<ReturnType<typeof getAvailablePromotions>>, TError = ErrorType<ErrorVO>>(
 params: GetAvailablePromotionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvailablePromotions>>,
          TError,
          Awaited<ReturnType<typeof getAvailablePromotions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvailablePromotions<TData = Awaited<ReturnType<typeof getAvailablePromotions>>, TError = ErrorType<ErrorVO>>(
 params: GetAvailablePromotionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvailablePromotions>>,
          TError,
          Awaited<ReturnType<typeof getAvailablePromotions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvailablePromotions<TData = Awaited<ReturnType<typeof getAvailablePromotions>>, TError = ErrorType<ErrorVO>>(
 params: GetAvailablePromotionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotions>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get available promotions for a user
 */

export function useGetAvailablePromotions<TData = Awaited<ReturnType<typeof getAvailablePromotions>>, TError = ErrorType<ErrorVO>>(
 params: GetAvailablePromotionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotions>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAvailablePromotionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns promotions that a user can use for a given order value
 * @summary Get promotions applicable for an order
 */
export const getAvailablePromotionsForOrder = (
    params: GetAvailablePromotionsForOrderParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<PromotionResponseDTO[]>(
      {url: `/api/v1/user-promotions/available-for-order`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAvailablePromotionsForOrderQueryKey = (params?: GetAvailablePromotionsForOrderParams,) => {
    return [
    `/api/v1/user-promotions/available-for-order`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAvailablePromotionsForOrderQueryOptions = <TData = Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError = ErrorType<ErrorVO>>(params: GetAvailablePromotionsForOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAvailablePromotionsForOrderQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>> = ({ signal }) => getAvailablePromotionsForOrder(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAvailablePromotionsForOrderQueryResult = NonNullable<Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>>
export type GetAvailablePromotionsForOrderQueryError = ErrorType<ErrorVO>


export function useGetAvailablePromotionsForOrder<TData = Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError = ErrorType<ErrorVO>>(
 params: GetAvailablePromotionsForOrderParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>,
          TError,
          Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvailablePromotionsForOrder<TData = Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError = ErrorType<ErrorVO>>(
 params: GetAvailablePromotionsForOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>,
          TError,
          Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvailablePromotionsForOrder<TData = Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError = ErrorType<ErrorVO>>(
 params: GetAvailablePromotionsForOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get promotions applicable for an order
 */

export function useGetAvailablePromotionsForOrder<TData = Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError = ErrorType<ErrorVO>>(
 params: GetAvailablePromotionsForOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailablePromotionsForOrder>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAvailablePromotionsForOrderQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




