/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CategoryRequestDTO,
  CategoryResponseDTO,
  ErrorVO,
  GetAllProductCategoriesParams,
  PageVOCategoryResponseDTO
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a product category by its ID.
 * @summary Get product category by ID
 */
export const getProductCategoryById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<CategoryResponseDTO>(
      {url: `/api/v1/product-categories/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetProductCategoryByIdQueryKey = (id?: number,) => {
    return [
    `/api/v1/product-categories/${id}`
    ] as const;
    }

    
export const getGetProductCategoryByIdQueryOptions = <TData = Awaited<ReturnType<typeof getProductCategoryById>>, TError = ErrorType<ErrorVO>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductCategoryById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductCategoryByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductCategoryById>>> = ({ signal }) => getProductCategoryById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductCategoryById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductCategoryByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProductCategoryById>>>
export type GetProductCategoryByIdQueryError = ErrorType<ErrorVO>


export function useGetProductCategoryById<TData = Awaited<ReturnType<typeof getProductCategoryById>>, TError = ErrorType<ErrorVO>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductCategoryById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductCategoryById>>,
          TError,
          Awaited<ReturnType<typeof getProductCategoryById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductCategoryById<TData = Awaited<ReturnType<typeof getProductCategoryById>>, TError = ErrorType<ErrorVO>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductCategoryById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductCategoryById>>,
          TError,
          Awaited<ReturnType<typeof getProductCategoryById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductCategoryById<TData = Awaited<ReturnType<typeof getProductCategoryById>>, TError = ErrorType<ErrorVO>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductCategoryById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get product category by ID
 */

export function useGetProductCategoryById<TData = Awaited<ReturnType<typeof getProductCategoryById>>, TError = ErrorType<ErrorVO>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductCategoryById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductCategoryByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing product category.
 * @summary Update a product category
 */
export const updateProductCategory = (
    id: number,
    categoryRequestDTO: BodyType<CategoryRequestDTO>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      const formData = new FormData();
formData.append(`name`, categoryRequestDTO.name)
if(categoryRequestDTO.description !== undefined) {
 formData.append(`description`, categoryRequestDTO.description)
 }
if(categoryRequestDTO.image !== undefined) {
 formData.append(`image`, categoryRequestDTO.image)
 }

      return axiosInstanceFn<CategoryResponseDTO>(
      {url: `/api/v1/product-categories/${id}`, method: 'PUT',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  


export const getUpdateProductCategoryMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProductCategory>>, TError,{id: number;data: BodyType<CategoryRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProductCategory>>, TError,{id: number;data: BodyType<CategoryRequestDTO>}, TContext> => {

const mutationKey = ['updateProductCategory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProductCategory>>, {id: number;data: BodyType<CategoryRequestDTO>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProductCategory(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProductCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof updateProductCategory>>>
    export type UpdateProductCategoryMutationBody = BodyType<CategoryRequestDTO>
    export type UpdateProductCategoryMutationError = ErrorType<ErrorVO>

    /**
 * @summary Update a product category
 */
export const useUpdateProductCategory = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProductCategory>>, TError,{id: number;data: BodyType<CategoryRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProductCategory>>,
        TError,
        {id: number;data: BodyType<CategoryRequestDTO>},
        TContext
      > => {

      const mutationOptions = getUpdateProductCategoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a product category by its ID.
 * @summary Delete a product category
 */
export const deleteProductCategory = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<void>(
      {url: `/api/v1/product-categories/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteProductCategoryMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProductCategory>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProductCategory>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteProductCategory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProductCategory>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteProductCategory(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProductCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProductCategory>>>
    
    export type DeleteProductCategoryMutationError = ErrorType<ErrorVO>

    /**
 * @summary Delete a product category
 */
export const useDeleteProductCategory = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProductCategory>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProductCategory>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteProductCategoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of all product categories.
 * @summary Get all product categories
 */
export const getAllProductCategories = (
    params: GetAllProductCategoriesParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<PageVOCategoryResponseDTO>(
      {url: `/api/v1/product-categories`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllProductCategoriesQueryKey = (params?: GetAllProductCategoriesParams,) => {
    return [
    `/api/v1/product-categories`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllProductCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getAllProductCategories>>, TError = ErrorType<ErrorVO>>(params: GetAllProductCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProductCategories>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllProductCategoriesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllProductCategories>>> = ({ signal }) => getAllProductCategories(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllProductCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllProductCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllProductCategories>>>
export type GetAllProductCategoriesQueryError = ErrorType<ErrorVO>


export function useGetAllProductCategories<TData = Awaited<ReturnType<typeof getAllProductCategories>>, TError = ErrorType<ErrorVO>>(
 params: GetAllProductCategoriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProductCategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProductCategories>>,
          TError,
          Awaited<ReturnType<typeof getAllProductCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProductCategories<TData = Awaited<ReturnType<typeof getAllProductCategories>>, TError = ErrorType<ErrorVO>>(
 params: GetAllProductCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProductCategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProductCategories>>,
          TError,
          Awaited<ReturnType<typeof getAllProductCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProductCategories<TData = Awaited<ReturnType<typeof getAllProductCategories>>, TError = ErrorType<ErrorVO>>(
 params: GetAllProductCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProductCategories>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all product categories
 */

export function useGetAllProductCategories<TData = Awaited<ReturnType<typeof getAllProductCategories>>, TError = ErrorType<ErrorVO>>(
 params: GetAllProductCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProductCategories>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllProductCategoriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new product category.
 * @summary Create a new product category
 */
export const createProductCategory = (
    categoryRequestDTO: BodyType<CategoryRequestDTO>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`name`, categoryRequestDTO.name)
if(categoryRequestDTO.description !== undefined) {
 formData.append(`description`, categoryRequestDTO.description)
 }
if(categoryRequestDTO.image !== undefined) {
 formData.append(`image`, categoryRequestDTO.image)
 }

      return axiosInstanceFn<CategoryResponseDTO>(
      {url: `/api/v1/product-categories`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }
  


export const getCreateProductCategoryMutationOptions = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProductCategory>>, TError,{data: BodyType<CategoryRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createProductCategory>>, TError,{data: BodyType<CategoryRequestDTO>}, TContext> => {

const mutationKey = ['createProductCategory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProductCategory>>, {data: BodyType<CategoryRequestDTO>}> = (props) => {
          const {data} = props ?? {};

          return  createProductCategory(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProductCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof createProductCategory>>>
    export type CreateProductCategoryMutationBody = BodyType<CategoryRequestDTO>
    export type CreateProductCategoryMutationError = ErrorType<ErrorVO>

    /**
 * @summary Create a new product category
 */
export const useCreateProductCategory = <TError = ErrorType<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProductCategory>>, TError,{data: BodyType<CategoryRequestDTO>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProductCategory>>,
        TError,
        {data: BodyType<CategoryRequestDTO>},
        TContext
      > => {

      const mutationOptions = getCreateProductCategoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    