/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Retrieve a product category by its ID.
 * @summary Get product category by ID
 */
export const getProductCategoryByIdParams = zod.object({
  "id": zod.number()
})

/**
 * Update an existing product category.
 * @summary Update a product category
 */
export const updateProductCategoryParams = zod.object({
  "id": zod.number()
})

export const updateProductCategoryBody = zod.object({
  "name": zod.string(),
  "description": zod.string().optional(),
  "image": zod.instanceof(File).optional()
})

/**
 * Delete a product category by its ID.
 * @summary Delete a product category
 */
export const deleteProductCategoryParams = zod.object({
  "id": zod.number()
})

/**
 * Retrieve a list of all product categories.
 * @summary Get all product categories
 */
export const getAllProductCategoriesQueryPageDefault = 0;
export const getAllProductCategoriesQueryPageMin = 0;

export const getAllProductCategoriesQuerySizeDefault = 20;



export const getAllProductCategoriesQueryParams = zod.object({
  "page": zod.number().min(getAllProductCategoriesQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getAllProductCategoriesQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.object({

})
})

/**
 * Create a new product category.
 * @summary Create a new product category
 */
export const createProductCategoryBody = zod.object({
  "name": zod.string(),
  "description": zod.string().optional(),
  "image": zod.instanceof(File).optional()
})

