/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorVO,
  GetImageStoragePathParams
} from '../../types';





/**
 * Returns an image or file stored in the server as a stream using the given relative URL path.
 * @summary Get image resource by file URL
 */
export const getImageStoragePath = (
    params: GetImageStoragePathParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    
    
    return axios.default.get(
      `/api/v1/storage/images`,{
        responseType: 'blob',
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetImageStoragePathQueryKey = (params?: GetImageStoragePathParams,) => {
    return [
    `/api/v1/storage/images`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetImageStoragePathQueryOptions = <TData = Awaited<ReturnType<typeof getImageStoragePath>>, TError = AxiosError<ErrorVO | Blob>>(params: GetImageStoragePathParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getImageStoragePath>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetImageStoragePathQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getImageStoragePath>>> = ({ signal }) => getImageStoragePath(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getImageStoragePath>>, TError, TData> & { queryKey: QueryKey }
}

export type GetImageStoragePathQueryResult = NonNullable<Awaited<ReturnType<typeof getImageStoragePath>>>
export type GetImageStoragePathQueryError = AxiosError<ErrorVO | Blob>


/**
 * @summary Get image resource by file URL
 */

export function useGetImageStoragePath<TData = Awaited<ReturnType<typeof getImageStoragePath>>, TError = AxiosError<ErrorVO | Blob>>(
 params: GetImageStoragePathParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getImageStoragePath>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetImageStoragePathQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




