/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorVO,
  GetImageStoragePathParams
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns an image or file stored in the server as a stream using the given relative URL path.
 * @summary Get image resource by file URL
 */
export const getImageStoragePath = (
    params: GetImageStoragePathParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<Blob>(
      {url: `/api/v1/storage/images`, method: 'GET',
        params,
        responseType: 'blob', signal
    },
      options);
    }
  



export const getGetImageStoragePathQueryKey = (params?: GetImageStoragePathParams,) => {
    return [
    `/api/v1/storage/images`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetImageStoragePathQueryOptions = <TData = Awaited<ReturnType<typeof getImageStoragePath>>, TError = ErrorType<ErrorVO | Blob>>(params: GetImageStoragePathParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageStoragePath>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetImageStoragePathQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getImageStoragePath>>> = ({ signal }) => getImageStoragePath(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getImageStoragePath>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetImageStoragePathQueryResult = NonNullable<Awaited<ReturnType<typeof getImageStoragePath>>>
export type GetImageStoragePathQueryError = ErrorType<ErrorVO | Blob>


export function useGetImageStoragePath<TData = Awaited<ReturnType<typeof getImageStoragePath>>, TError = ErrorType<ErrorVO | Blob>>(
 params: GetImageStoragePathParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageStoragePath>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getImageStoragePath>>,
          TError,
          Awaited<ReturnType<typeof getImageStoragePath>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetImageStoragePath<TData = Awaited<ReturnType<typeof getImageStoragePath>>, TError = ErrorType<ErrorVO | Blob>>(
 params: GetImageStoragePathParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageStoragePath>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getImageStoragePath>>,
          TError,
          Awaited<ReturnType<typeof getImageStoragePath>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetImageStoragePath<TData = Awaited<ReturnType<typeof getImageStoragePath>>, TError = ErrorType<ErrorVO | Blob>>(
 params: GetImageStoragePathParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageStoragePath>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get image resource by file URL
 */

export function useGetImageStoragePath<TData = Awaited<ReturnType<typeof getImageStoragePath>>, TError = ErrorType<ErrorVO | Blob>>(
 params: GetImageStoragePathParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageStoragePath>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetImageStoragePathQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




