/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorVO,
  GetActiveOrderCountByStatus200,
  GetRevenueStatsForMonthOrQuarter200,
  GetRevenueStatsForMonthOrQuarterParams,
  GetRevenueStatsParams,
  GetSoldByCategory200,
  GetSoldByCategoryParams,
  RevenueStatsResponseDTO
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the number of orders in PENDING, CONFIRMED, and PROCESSING states.
 * @summary Get total order count for statuses: PENDING, CONFIRMED, PROCESSING
 */
export const getActiveOrderCountByStatus = (
    
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<GetActiveOrderCountByStatus200>(
      {url: `/api/v1/stats/total-order-count-by-status/active`, method: 'GET', signal
    },
      options);
    }
  



export const getGetActiveOrderCountByStatusQueryKey = () => {
    return [
    `/api/v1/stats/total-order-count-by-status/active`
    ] as const;
    }

    
export const getGetActiveOrderCountByStatusQueryOptions = <TData = Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActiveOrderCountByStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActiveOrderCountByStatus>>> = ({ signal }) => getActiveOrderCountByStatus(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetActiveOrderCountByStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getActiveOrderCountByStatus>>>
export type GetActiveOrderCountByStatusQueryError = ErrorType<unknown>


export function useGetActiveOrderCountByStatus<TData = Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveOrderCountByStatus>>,
          TError,
          Awaited<ReturnType<typeof getActiveOrderCountByStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActiveOrderCountByStatus<TData = Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveOrderCountByStatus>>,
          TError,
          Awaited<ReturnType<typeof getActiveOrderCountByStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActiveOrderCountByStatus<TData = Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get total order count for statuses: PENDING, CONFIRMED, PROCESSING
 */

export function useGetActiveOrderCountByStatus<TData = Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetActiveOrderCountByStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns revenue statistics grouped by day, week, or month within a specific time range.
 * @summary Get revenue statistics
 */
export const getRevenueStats = (
    params?: GetRevenueStatsParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<RevenueStatsResponseDTO[]>(
      {url: `/api/v1/stats/revenue`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetRevenueStatsQueryKey = (params?: GetRevenueStatsParams,) => {
    return [
    `/api/v1/stats/revenue`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRevenueStatsQueryOptions = <TData = Awaited<ReturnType<typeof getRevenueStats>>, TError = ErrorType<ErrorVO>>(params?: GetRevenueStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueStats>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRevenueStatsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRevenueStats>>> = ({ signal }) => getRevenueStats(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRevenueStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRevenueStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getRevenueStats>>>
export type GetRevenueStatsQueryError = ErrorType<ErrorVO>


export function useGetRevenueStats<TData = Awaited<ReturnType<typeof getRevenueStats>>, TError = ErrorType<ErrorVO>>(
 params: undefined |  GetRevenueStatsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRevenueStats>>,
          TError,
          Awaited<ReturnType<typeof getRevenueStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRevenueStats<TData = Awaited<ReturnType<typeof getRevenueStats>>, TError = ErrorType<ErrorVO>>(
 params?: GetRevenueStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRevenueStats>>,
          TError,
          Awaited<ReturnType<typeof getRevenueStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRevenueStats<TData = Awaited<ReturnType<typeof getRevenueStats>>, TError = ErrorType<ErrorVO>>(
 params?: GetRevenueStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueStats>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get revenue statistics
 */

export function useGetRevenueStats<TData = Awaited<ReturnType<typeof getRevenueStats>>, TError = ErrorType<ErrorVO>>(
 params?: GetRevenueStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueStats>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRevenueStatsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns revenue statistics grouped by day by month or quarter of year.
 * @summary Get revenue statistics by month or quarter of the year
 */
export const getRevenueStatsForMonthOrQuarter = (
    params: GetRevenueStatsForMonthOrQuarterParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<GetRevenueStatsForMonthOrQuarter200>(
      {url: `/api/v1/stats/revenue/month-or-quarter`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetRevenueStatsForMonthOrQuarterQueryKey = (params?: GetRevenueStatsForMonthOrQuarterParams,) => {
    return [
    `/api/v1/stats/revenue/month-or-quarter`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRevenueStatsForMonthOrQuarterQueryOptions = <TData = Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError = ErrorType<unknown>>(params: GetRevenueStatsForMonthOrQuarterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRevenueStatsForMonthOrQuarterQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>> = ({ signal }) => getRevenueStatsForMonthOrQuarter(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRevenueStatsForMonthOrQuarterQueryResult = NonNullable<Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>>
export type GetRevenueStatsForMonthOrQuarterQueryError = ErrorType<unknown>


export function useGetRevenueStatsForMonthOrQuarter<TData = Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError = ErrorType<unknown>>(
 params: GetRevenueStatsForMonthOrQuarterParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>,
          TError,
          Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRevenueStatsForMonthOrQuarter<TData = Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError = ErrorType<unknown>>(
 params: GetRevenueStatsForMonthOrQuarterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>,
          TError,
          Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRevenueStatsForMonthOrQuarter<TData = Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError = ErrorType<unknown>>(
 params: GetRevenueStatsForMonthOrQuarterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get revenue statistics by month or quarter of the year
 */

export function useGetRevenueStatsForMonthOrQuarter<TData = Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError = ErrorType<unknown>>(
 params: GetRevenueStatsForMonthOrQuarterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRevenueStatsForMonthOrQuarterQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns revenue statistics grouped by year.
 * @summary Get revenue statistics by year
 */
export const getSoldByCategory = (
    params: GetSoldByCategoryParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<GetSoldByCategory200>(
      {url: `/api/v1/stats/get-sold-by-category`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetSoldByCategoryQueryKey = (params?: GetSoldByCategoryParams,) => {
    return [
    `/api/v1/stats/get-sold-by-category`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetSoldByCategoryQueryOptions = <TData = Awaited<ReturnType<typeof getSoldByCategory>>, TError = ErrorType<unknown>>(params: GetSoldByCategoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSoldByCategory>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSoldByCategoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSoldByCategory>>> = ({ signal }) => getSoldByCategory(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSoldByCategory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSoldByCategoryQueryResult = NonNullable<Awaited<ReturnType<typeof getSoldByCategory>>>
export type GetSoldByCategoryQueryError = ErrorType<unknown>


export function useGetSoldByCategory<TData = Awaited<ReturnType<typeof getSoldByCategory>>, TError = ErrorType<unknown>>(
 params: GetSoldByCategoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSoldByCategory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSoldByCategory>>,
          TError,
          Awaited<ReturnType<typeof getSoldByCategory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSoldByCategory<TData = Awaited<ReturnType<typeof getSoldByCategory>>, TError = ErrorType<unknown>>(
 params: GetSoldByCategoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSoldByCategory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSoldByCategory>>,
          TError,
          Awaited<ReturnType<typeof getSoldByCategory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSoldByCategory<TData = Awaited<ReturnType<typeof getSoldByCategory>>, TError = ErrorType<unknown>>(
 params: GetSoldByCategoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSoldByCategory>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get revenue statistics by year
 */

export function useGetSoldByCategory<TData = Awaited<ReturnType<typeof getSoldByCategory>>, TError = ErrorType<unknown>>(
 params: GetSoldByCategoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSoldByCategory>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSoldByCategoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




