/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorVO,
  GetActiveOrderCountByStatus200,
  GetRevenueStatsForMonthOrQuarter200,
  GetRevenueStatsForMonthOrQuarterParams,
  GetRevenueStatsParams,
  GetSoldByCategory200,
  GetSoldByCategoryParams,
  RevenueStatsResponseDTO
} from '../../types';





/**
 * Returns the number of orders in PENDING, CONFIRMED, and PROCESSING states.
 * @summary Get total order count for statuses: PENDING, CONFIRMED, PROCESSING
 */
export const getActiveOrderCountByStatus = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetActiveOrderCountByStatus200>> => {
    
    
    return axios.default.get(
      `/api/v1/stats/total-order-count-by-status/active`,options
    );
  }




export const getGetActiveOrderCountByStatusQueryKey = () => {
    return [
    `/api/v1/stats/total-order-count-by-status/active`
    ] as const;
    }

    
export const getGetActiveOrderCountByStatusQueryOptions = <TData = Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActiveOrderCountByStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActiveOrderCountByStatus>>> = ({ signal }) => getActiveOrderCountByStatus({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type GetActiveOrderCountByStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getActiveOrderCountByStatus>>>
export type GetActiveOrderCountByStatusQueryError = AxiosError<unknown>


/**
 * @summary Get total order count for statuses: PENDING, CONFIRMED, PROCESSING
 */

export function useGetActiveOrderCountByStatus<TData = Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getActiveOrderCountByStatus>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetActiveOrderCountByStatusQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns revenue statistics grouped by day, week, or month within a specific time range.
 * @summary Get revenue statistics
 */
export const getRevenueStats = (
    params?: GetRevenueStatsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RevenueStatsResponseDTO[]>> => {
    
    
    return axios.default.get(
      `/api/v1/stats/revenue`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetRevenueStatsQueryKey = (params?: GetRevenueStatsParams,) => {
    return [
    `/api/v1/stats/revenue`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRevenueStatsQueryOptions = <TData = Awaited<ReturnType<typeof getRevenueStats>>, TError = AxiosError<ErrorVO>>(params?: GetRevenueStatsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRevenueStats>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRevenueStatsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRevenueStats>>> = ({ signal }) => getRevenueStats(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRevenueStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRevenueStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getRevenueStats>>>
export type GetRevenueStatsQueryError = AxiosError<ErrorVO>


/**
 * @summary Get revenue statistics
 */

export function useGetRevenueStats<TData = Awaited<ReturnType<typeof getRevenueStats>>, TError = AxiosError<ErrorVO>>(
 params?: GetRevenueStatsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRevenueStats>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRevenueStatsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns revenue statistics grouped by day by month or quarter of year.
 * @summary Get revenue statistics by month or quarter of the year
 */
export const getRevenueStatsForMonthOrQuarter = (
    params: GetRevenueStatsForMonthOrQuarterParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetRevenueStatsForMonthOrQuarter200>> => {
    
    
    return axios.default.get(
      `/api/v1/stats/revenue/month-or-quarter`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetRevenueStatsForMonthOrQuarterQueryKey = (params?: GetRevenueStatsForMonthOrQuarterParams,) => {
    return [
    `/api/v1/stats/revenue/month-or-quarter`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRevenueStatsForMonthOrQuarterQueryOptions = <TData = Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError = AxiosError<unknown>>(params: GetRevenueStatsForMonthOrQuarterParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRevenueStatsForMonthOrQuarterQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>> = ({ signal }) => getRevenueStatsForMonthOrQuarter(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRevenueStatsForMonthOrQuarterQueryResult = NonNullable<Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>>
export type GetRevenueStatsForMonthOrQuarterQueryError = AxiosError<unknown>


/**
 * @summary Get revenue statistics by month or quarter of the year
 */

export function useGetRevenueStatsForMonthOrQuarter<TData = Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError = AxiosError<unknown>>(
 params: GetRevenueStatsForMonthOrQuarterParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRevenueStatsForMonthOrQuarter>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRevenueStatsForMonthOrQuarterQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns revenue statistics grouped by year.
 * @summary Get revenue statistics by year
 */
export const getSoldByCategory = (
    params: GetSoldByCategoryParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetSoldByCategory200>> => {
    
    
    return axios.default.get(
      `/api/v1/stats/get-sold-by-category`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetSoldByCategoryQueryKey = (params?: GetSoldByCategoryParams,) => {
    return [
    `/api/v1/stats/get-sold-by-category`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetSoldByCategoryQueryOptions = <TData = Awaited<ReturnType<typeof getSoldByCategory>>, TError = AxiosError<unknown>>(params: GetSoldByCategoryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSoldByCategory>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSoldByCategoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSoldByCategory>>> = ({ signal }) => getSoldByCategory(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSoldByCategory>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSoldByCategoryQueryResult = NonNullable<Awaited<ReturnType<typeof getSoldByCategory>>>
export type GetSoldByCategoryQueryError = AxiosError<unknown>


/**
 * @summary Get revenue statistics by year
 */

export function useGetSoldByCategory<TData = Awaited<ReturnType<typeof getSoldByCategory>>, TError = AxiosError<unknown>>(
 params: GetSoldByCategoryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSoldByCategory>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSoldByCategoryQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




