/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthResponseDTO,
  ErrorVO,
  FirebaseLoginRequestDTO,
  FirebaseRegisterRequestDTO,
  ForgotPasswordRequestDTO,
  GoogleLoginRequestDTO,
  GoogleRegisterRequestDTO,
  LoginRequestDTO,
  LoginWith2FAChallengeParams,
  PasswordChangeDTO,
  RefreshTokenRequestDTO,
  RegisterRequestDTO,
  SendOTPRequestDTO,
  SendVerifyEmailRequestDTO,
  UserResponseDTO,
  VerifyEmailParams,
  VerifyOTPRequestDTO,
  VerifyOTPResponseDTO
} from '../../types';





export const verifyOTP = (
    verifyOTPRequestDTO: VerifyOTPRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VerifyOTPResponseDTO>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/verify-otp`,
      verifyOTPRequestDTO,options
    );
  }



export const getVerifyOTPMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyOTP>>, TError,{data: VerifyOTPRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof verifyOTP>>, TError,{data: VerifyOTPRequestDTO}, TContext> => {

const mutationKey = ['verifyOTP'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyOTP>>, {data: VerifyOTPRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  verifyOTP(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyOTPMutationResult = NonNullable<Awaited<ReturnType<typeof verifyOTP>>>
    export type VerifyOTPMutationBody = VerifyOTPRequestDTO
    export type VerifyOTPMutationError = AxiosError<unknown>

    export const useVerifyOTP = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyOTP>>, TError,{data: VerifyOTPRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof verifyOTP>>,
        TError,
        {data: VerifyOTPRequestDTO},
        TContext
      > => {

      const mutationOptions = getVerifyOTPMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Resend verification email
 */
export const sendVerifyEmail = (
    sendVerifyEmailRequestDTO: SendVerifyEmailRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/send-verify-email`,
      sendVerifyEmailRequestDTO,options
    );
  }



export const getSendVerifyEmailMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendVerifyEmail>>, TError,{data: SendVerifyEmailRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof sendVerifyEmail>>, TError,{data: SendVerifyEmailRequestDTO}, TContext> => {

const mutationKey = ['sendVerifyEmail'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendVerifyEmail>>, {data: SendVerifyEmailRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  sendVerifyEmail(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SendVerifyEmailMutationResult = NonNullable<Awaited<ReturnType<typeof sendVerifyEmail>>>
    export type SendVerifyEmailMutationBody = SendVerifyEmailRequestDTO
    export type SendVerifyEmailMutationError = AxiosError<unknown>

    /**
 * @summary Resend verification email
 */
export const useSendVerifyEmail = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendVerifyEmail>>, TError,{data: SendVerifyEmailRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof sendVerifyEmail>>,
        TError,
        {data: SendVerifyEmailRequestDTO},
        TContext
      > => {

      const mutationOptions = getSendVerifyEmailMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const sendOTP = (
    sendOTPRequestDTO: SendOTPRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/send-otp`,
      sendOTPRequestDTO,options
    );
  }



export const getSendOTPMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendOTP>>, TError,{data: SendOTPRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof sendOTP>>, TError,{data: SendOTPRequestDTO}, TContext> => {

const mutationKey = ['sendOTP'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendOTP>>, {data: SendOTPRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  sendOTP(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SendOTPMutationResult = NonNullable<Awaited<ReturnType<typeof sendOTP>>>
    export type SendOTPMutationBody = SendOTPRequestDTO
    export type SendOTPMutationError = AxiosError<unknown>

    export const useSendOTP = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendOTP>>, TError,{data: SendOTPRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof sendOTP>>,
        TError,
        {data: SendOTPRequestDTO},
        TContext
      > => {

      const mutationOptions = getSendOTPMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Register a new user
 */
export const register = (
    registerRequestDTO: RegisterRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponseDTO>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/register`,
      registerRequestDTO,options
    );
  }



export const getRegisterMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequestDTO}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: RegisterRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  register(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = RegisterRequestDTO
    export type RegisterMutationError = AxiosError<ErrorVO>

    /**
 * @summary Register a new user
 */
export const useRegister = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: RegisterRequestDTO},
        TContext
      > => {

      const mutationOptions = getRegisterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Refresh access token using refresh token
 */
export const refreshToken = (
    refreshTokenRequestDTO: RefreshTokenRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponseDTO>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/refresh`,
      refreshTokenRequestDTO,options
    );
  }



export const getRefreshTokenMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshTokenRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshTokenRequestDTO}, TContext> => {

const mutationKey = ['refreshToken'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshToken>>, {data: RefreshTokenRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  refreshToken(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>
    export type RefreshTokenMutationBody = RefreshTokenRequestDTO
    export type RefreshTokenMutationError = AxiosError<ErrorVO>

    /**
 * @summary Refresh access token using refresh token
 */
export const useRefreshToken = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshTokenRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof refreshToken>>,
        TError,
        {data: RefreshTokenRequestDTO},
        TContext
      > => {

      const mutationOptions = getRefreshTokenMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Register using Google OAuth2 credentials. The Google ID token is sent in the request body.
 * @summary Register with Google OAuth2
 */
export const registerWithGoogle = (
    googleRegisterRequestDTO: GoogleRegisterRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/oauth2/register/google`,
      googleRegisterRequestDTO,options
    );
  }



export const getRegisterWithGoogleMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerWithGoogle>>, TError,{data: GoogleRegisterRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof registerWithGoogle>>, TError,{data: GoogleRegisterRequestDTO}, TContext> => {

const mutationKey = ['registerWithGoogle'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerWithGoogle>>, {data: GoogleRegisterRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  registerWithGoogle(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterWithGoogleMutationResult = NonNullable<Awaited<ReturnType<typeof registerWithGoogle>>>
    export type RegisterWithGoogleMutationBody = GoogleRegisterRequestDTO
    export type RegisterWithGoogleMutationError = AxiosError<ErrorVO>

    /**
 * @summary Register with Google OAuth2
 */
export const useRegisterWithGoogle = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerWithGoogle>>, TError,{data: GoogleRegisterRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof registerWithGoogle>>,
        TError,
        {data: GoogleRegisterRequestDTO},
        TContext
      > => {

      const mutationOptions = getRegisterWithGoogleMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Register using Firebase credentials. The Firebase ID token is sent in the request body.
 * @summary Register with Firebase
 */
export const registerWithFirebase = (
    firebaseRegisterRequestDTO: FirebaseRegisterRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/oauth2/register/firebase`,
      firebaseRegisterRequestDTO,options
    );
  }



export const getRegisterWithFirebaseMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerWithFirebase>>, TError,{data: FirebaseRegisterRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof registerWithFirebase>>, TError,{data: FirebaseRegisterRequestDTO}, TContext> => {

const mutationKey = ['registerWithFirebase'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerWithFirebase>>, {data: FirebaseRegisterRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  registerWithFirebase(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterWithFirebaseMutationResult = NonNullable<Awaited<ReturnType<typeof registerWithFirebase>>>
    export type RegisterWithFirebaseMutationBody = FirebaseRegisterRequestDTO
    export type RegisterWithFirebaseMutationError = AxiosError<ErrorVO>

    /**
 * @summary Register with Firebase
 */
export const useRegisterWithFirebase = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerWithFirebase>>, TError,{data: FirebaseRegisterRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof registerWithFirebase>>,
        TError,
        {data: FirebaseRegisterRequestDTO},
        TContext
      > => {

      const mutationOptions = getRegisterWithFirebaseMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Login using Google OAuth2 credentials. The Google ID token is sent in the request body.
 * @summary Login with Google OAuth2
 */
export const loginWithGoogle = (
    googleLoginRequestDTO: GoogleLoginRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/oauth2/login/google`,
      googleLoginRequestDTO,options
    );
  }



export const getLoginWithGoogleMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginWithGoogle>>, TError,{data: GoogleLoginRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof loginWithGoogle>>, TError,{data: GoogleLoginRequestDTO}, TContext> => {

const mutationKey = ['loginWithGoogle'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginWithGoogle>>, {data: GoogleLoginRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  loginWithGoogle(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginWithGoogleMutationResult = NonNullable<Awaited<ReturnType<typeof loginWithGoogle>>>
    export type LoginWithGoogleMutationBody = GoogleLoginRequestDTO
    export type LoginWithGoogleMutationError = AxiosError<ErrorVO>

    /**
 * @summary Login with Google OAuth2
 */
export const useLoginWithGoogle = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginWithGoogle>>, TError,{data: GoogleLoginRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof loginWithGoogle>>,
        TError,
        {data: GoogleLoginRequestDTO},
        TContext
      > => {

      const mutationOptions = getLoginWithGoogleMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Login using Firebase credentials. The Firebase ID token is sent in the request body.
 * @summary Login with Firebase
 */
export const loginWithFirebase = (
    firebaseLoginRequestDTO: FirebaseLoginRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/oauth2/login/firebase`,
      firebaseLoginRequestDTO,options
    );
  }



export const getLoginWithFirebaseMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginWithFirebase>>, TError,{data: FirebaseLoginRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof loginWithFirebase>>, TError,{data: FirebaseLoginRequestDTO}, TContext> => {

const mutationKey = ['loginWithFirebase'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginWithFirebase>>, {data: FirebaseLoginRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  loginWithFirebase(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginWithFirebaseMutationResult = NonNullable<Awaited<ReturnType<typeof loginWithFirebase>>>
    export type LoginWithFirebaseMutationBody = FirebaseLoginRequestDTO
    export type LoginWithFirebaseMutationError = AxiosError<ErrorVO>

    /**
 * @summary Login with Firebase
 */
export const useLoginWithFirebase = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginWithFirebase>>, TError,{data: FirebaseLoginRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof loginWithFirebase>>,
        TError,
        {data: FirebaseLoginRequestDTO},
        TContext
      > => {

      const mutationOptions = getLoginWithFirebaseMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Log out user
 */
export const logout = (
    refreshTokenRequestDTO: RefreshTokenRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/logout`,
      refreshTokenRequestDTO,{
    ...options,}
    );
  }



export const getLogoutMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: RefreshTokenRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: RefreshTokenRequestDTO}, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, {data: RefreshTokenRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  logout(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    export type LogoutMutationBody = RefreshTokenRequestDTO
    export type LogoutMutationError = AxiosError<ErrorVO>

    /**
 * @summary Log out user
 */
export const useLogout = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: RefreshTokenRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        {data: RefreshTokenRequestDTO},
        TContext
      > => {

      const mutationOptions = getLogoutMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * credentialId is usually the email or phone number or username
 * @summary Login with credentialId and password
 */
export const login = (
    loginRequestDTO: LoginRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponseDTO>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/login`,
      loginRequestDTO,options
    );
  }



export const getLoginMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequestDTO}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  login(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginRequestDTO
    export type LoginMutationError = AxiosError<ErrorVO>

    /**
 * @summary Login with credentialId and password
 */
export const useLogin = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginRequestDTO},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const loginWith2FAChallenge = (
    params: LoginWith2FAChallengeParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponseDTO>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/login-challenge`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getLoginWith2FAChallengeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginWith2FAChallenge>>, TError,{params: LoginWith2FAChallengeParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof loginWith2FAChallenge>>, TError,{params: LoginWith2FAChallengeParams}, TContext> => {

const mutationKey = ['loginWith2FAChallenge'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginWith2FAChallenge>>, {params: LoginWith2FAChallengeParams}> = (props) => {
          const {params} = props ?? {};

          return  loginWith2FAChallenge(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginWith2FAChallengeMutationResult = NonNullable<Awaited<ReturnType<typeof loginWith2FAChallenge>>>
    
    export type LoginWith2FAChallengeMutationError = AxiosError<unknown>

    export const useLoginWith2FAChallenge = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginWith2FAChallenge>>, TError,{params: LoginWith2FAChallengeParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof loginWith2FAChallenge>>,
        TError,
        {params: LoginWith2FAChallengeParams},
        TContext
      > => {

      const mutationOptions = getLoginWith2FAChallengeMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const forgotPassword = (
    forgotPasswordRequestDTO: ForgotPasswordRequestDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/forgot-password`,
      forgotPasswordRequestDTO,{
    ...options,}
    );
  }



export const getForgotPasswordMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forgotPassword>>, TError,{data: ForgotPasswordRequestDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof forgotPassword>>, TError,{data: ForgotPasswordRequestDTO}, TContext> => {

const mutationKey = ['forgotPassword'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof forgotPassword>>, {data: ForgotPasswordRequestDTO}> = (props) => {
          const {data} = props ?? {};

          return  forgotPassword(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof forgotPassword>>>
    export type ForgotPasswordMutationBody = ForgotPasswordRequestDTO
    export type ForgotPasswordMutationError = AxiosError<unknown>

    export const useForgotPassword = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forgotPassword>>, TError,{data: ForgotPasswordRequestDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof forgotPassword>>,
        TError,
        {data: ForgotPasswordRequestDTO},
        TContext
      > => {

      const mutationOptions = getForgotPasswordMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Change user password
 */
export const changePassword = (
    passwordChangeDTO: PasswordChangeDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/change-password`,
      passwordChangeDTO,{
    ...options,}
    );
  }



export const getChangePasswordMutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: PasswordChangeDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: PasswordChangeDTO}, TContext> => {

const mutationKey = ['changePassword'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePassword>>, {data: PasswordChangeDTO}> = (props) => {
          const {data} = props ?? {};

          return  changePassword(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>
    export type ChangePasswordMutationBody = PasswordChangeDTO
    export type ChangePasswordMutationError = AxiosError<ErrorVO>

    /**
 * @summary Change user password
 */
export const useChangePassword = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: PasswordChangeDTO}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof changePassword>>,
        TError,
        {data: PasswordChangeDTO},
        TContext
      > => {

      const mutationOptions = getChangePasswordMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Verification email
 */
export const verifyEmail = (
    params: VerifyEmailParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.get(
      `/api/v1/auth/verify-email`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getVerifyEmailQueryKey = (params?: VerifyEmailParams,) => {
    return [
    `/api/v1/auth/verify-email`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getVerifyEmailQueryOptions = <TData = Awaited<ReturnType<typeof verifyEmail>>, TError = AxiosError<unknown>>(params: VerifyEmailParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVerifyEmailQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof verifyEmail>>> = ({ signal }) => verifyEmail(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData> & { queryKey: QueryKey }
}

export type VerifyEmailQueryResult = NonNullable<Awaited<ReturnType<typeof verifyEmail>>>
export type VerifyEmailQueryError = AxiosError<unknown>


/**
 * @summary Verification email
 */

export function useVerifyEmail<TData = Awaited<ReturnType<typeof verifyEmail>>, TError = AxiosError<unknown>>(
 params: VerifyEmailParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getVerifyEmailQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get current user information
 */
export const getCurrentUser = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponseDTO>> => {
    
    
    return axios.default.get(
      `/api/v1/auth/me`,options
    );
  }




export const getGetCurrentUserQueryKey = () => {
    return [
    `/api/v1/auth/me`
    ] as const;
    }

    
export const getGetCurrentUserQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = AxiosError<ErrorVO>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({ signal }) => getCurrentUser({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>
export type GetCurrentUserQueryError = AxiosError<ErrorVO>


/**
 * @summary Get current user information
 */

export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = AxiosError<ErrorVO>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCurrentUserQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




