/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Get shipper by ID
 */
export const getByIdParams = zod.object({
  "id": zod.number().describe('Shipper ID')
})

/**
 * @summary Update a shipper by ID
 */
export const update1Params = zod.object({
  "id": zod.number().describe('Shipper ID')
})

export const update1Body = zod.object({
  "fullname": zod.string(),
  "phone": zod.string(),
  "licensePlate": zod.string().optional()
})

/**
 * @summary Delete a shipper by ID
 */
export const delete1Params = zod.object({
  "id": zod.number().describe('Shipper ID')
})

/**
 * Supports pagination and filtering
 * @summary Get all shippers
 */
export const getAllQueryPageDefault = 0;
export const getAllQueryPageMin = 0;

export const getAllQuerySizeDefault = 20;



export const getAllQueryParams = zod.object({
  "page": zod.number().min(getAllQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getAllQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.object({

})
})

/**
 * @summary Create a new shipper
 */
export const create1Body = zod.object({
  "fullname": zod.string(),
  "phone": zod.string(),
  "licensePlate": zod.string().optional()
})

