/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SE114.P12
 * API cho dự án nhập môn ứng dụng di dộng
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorVO,
  GetAllParams,
  PageVO,
  ShipperRequest,
  ShipperResponse
} from '../../types';





/**
 * @summary Get shipper by ID
 */
export const getById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ShipperResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/shippers/${id}`,options
    );
  }




export const getGetByIdQueryKey = (id?: number,) => {
    return [
    `/api/v1/shippers/${id}`
    ] as const;
    }

    
export const getGetByIdQueryOptions = <TData = Awaited<ReturnType<typeof getById>>, TError = AxiosError<ErrorVO | ShipperResponse>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getById>>> = ({ signal }) => getById(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getById>>>
export type GetByIdQueryError = AxiosError<ErrorVO | ShipperResponse>


/**
 * @summary Get shipper by ID
 */

export function useGetById<TData = Awaited<ReturnType<typeof getById>>, TError = AxiosError<ErrorVO | ShipperResponse>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetByIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update a shipper by ID
 */
export const update1 = (
    id: number,
    shipperRequest: ShipperRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ShipperResponse>> => {
    
    
    return axios.default.put(
      `/api/v1/shippers/${id}`,
      shipperRequest,options
    );
  }



export const getUpdate1MutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update1>>, TError,{id: number;data: ShipperRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof update1>>, TError,{id: number;data: ShipperRequest}, TContext> => {

const mutationKey = ['update1'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof update1>>, {id: number;data: ShipperRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  update1(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Update1MutationResult = NonNullable<Awaited<ReturnType<typeof update1>>>
    export type Update1MutationBody = ShipperRequest
    export type Update1MutationError = AxiosError<ErrorVO>

    /**
 * @summary Update a shipper by ID
 */
export const useUpdate1 = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update1>>, TError,{id: number;data: ShipperRequest}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof update1>>,
        TError,
        {id: number;data: ShipperRequest},
        TContext
      > => {

      const mutationOptions = getUpdate1MutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete a shipper by ID
 */
export const delete1 = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/v1/shippers/${id}`,options
    );
  }



export const getDelete1MutationOptions = <TError = AxiosError<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete1>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof delete1>>, TError,{id: number}, TContext> => {

const mutationKey = ['delete1'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof delete1>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  delete1(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Delete1MutationResult = NonNullable<Awaited<ReturnType<typeof delete1>>>
    
    export type Delete1MutationError = AxiosError<ErrorVO | void>

    /**
 * @summary Delete a shipper by ID
 */
export const useDelete1 = <TError = AxiosError<ErrorVO | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete1>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof delete1>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDelete1MutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Supports pagination and filtering
 * @summary Get all shippers
 */
export const getAll = (
    params: GetAllParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PageVO>> => {
    
    
    return axios.default.get(
      `/api/v1/shippers`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAllQueryKey = (params?: GetAllParams,) => {
    return [
    `/api/v1/shippers`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllQueryOptions = <TData = Awaited<ReturnType<typeof getAll>>, TError = AxiosError<ErrorVO>>(params: GetAllParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAll>>> = ({ signal }) => getAll(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllQueryResult = NonNullable<Awaited<ReturnType<typeof getAll>>>
export type GetAllQueryError = AxiosError<ErrorVO>


/**
 * @summary Get all shippers
 */

export function useGetAll<TData = Awaited<ReturnType<typeof getAll>>, TError = AxiosError<ErrorVO>>(
 params: GetAllParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a new shipper
 */
export const create1 = (
    shipperRequest: ShipperRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ShipperResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/shippers`,
      shipperRequest,options
    );
  }



export const getCreate1MutationOptions = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create1>>, TError,{data: ShipperRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof create1>>, TError,{data: ShipperRequest}, TContext> => {

const mutationKey = ['create1'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof create1>>, {data: ShipperRequest}> = (props) => {
          const {data} = props ?? {};

          return  create1(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Create1MutationResult = NonNullable<Awaited<ReturnType<typeof create1>>>
    export type Create1MutationBody = ShipperRequest
    export type Create1MutationError = AxiosError<ErrorVO>

    /**
 * @summary Create a new shipper
 */
export const useCreate1 = <TError = AxiosError<ErrorVO>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create1>>, TError,{data: ShipperRequest}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof create1>>,
        TError,
        {data: ShipperRequest},
        TContext
      > => {

      const mutationOptions = getCreate1MutationOptions(options);

      return useMutation(mutationOptions);
    }
    